"""E1 cross-host numeric/canonical vector replay lock (Python reference side).

Replays the frozen vector file generated by tests/generate_e1_vectors.py
through the real sealed parser + canonical serializer + DeviceAIValue encoder
and asserts every recorded expectation still holds byte-for-byte:

- accepted vectors: canonical text AND utf8 hex, bare sha256, namespaced
  sha256, encoded DeviceAIValue (structural and serialized-byte form);
- rejected vectors: closed ProjectionError codes;
- cross-vector invariants (same-value/different-lexeme sha divergence,
  surrogate-pair-vs-raw canonical convergence, encode disambiguation);
- file self-consistency (counts, unique ids, input text/hex agreement) and
  provenance (the vector file pins the sha256 of the two reference sources).

Any drift in tire_api/device_ai_projection.py or device_ai_value_encoder.py,
or any silent edit of the vector file, turns this suite red. Regenerating the
file is a conscious act:
    ./.venv/Scripts/python.exe -B -X utf8 tests/generate_e1_vectors.py
followed by re-review of the diff. Pure tests: no DB, app import, env change
or network.
"""
import hashlib
import json
from pathlib import Path

import pytest

from tire_api import device_ai_value_encoder as encoder
from tire_api.device_ai_projection import (
    ProjectionError, canonical_exact_json, exact_digest, parse_exact_json,
)

REPO_ROOT = Path(__file__).resolve().parents[3]
VECTOR_FILE = REPO_ROOT / ".artifacts/device-ai50/specs/e1-canonical-vectors-a.json"
GENERATOR = REPO_ROOT / "apps/api/tests/generate_e1_vectors.py"
PINNED_SOURCES = {
    "device_ai_projection.py": REPO_ROOT / "apps/api/tire_api/device_ai_projection.py",
    "device_ai_value_encoder.py": REPO_ROOT / "apps/api/tire_api/device_ai_value_encoder.py",
}

PAYLOAD = json.loads(VECTOR_FILE.read_text(encoding="utf-8"))
VECTORS = {item["id"]: item for item in PAYLOAD["vectors"]}
ACCEPTED = [item for item in PAYLOAD["vectors"] if item["state"] == "accepted"]
REJECTED = [item for item in PAYLOAD["vectors"] if item["state"] == "rejected"]
REGENERATE_HINT = (
    f"vector file {VECTOR_FILE} is stale or tampered; regenerate it with "
    f"`{GENERATOR}` (python -B -X utf8, cwd apps/api) and re-review the diff")


def expand(inp: dict) -> bytes:
    if inp["form"] == "literal":
        return inp["text"].encode("utf-8")
    if inp["form"] == "bytes":
        return bytes.fromhex(inp["utf8_hex"])
    return (inp["prefix"] + inp["repeat"] * inp["count"] + inp["suffix"]).encode("utf-8")


def test_vector_file_schema_counts_and_internal_consistency():
    assert PAYLOAD["schema"] == "device-ai-e1-canonical-vectors@1"
    assert PAYLOAD["state"] == "generated_and_self_checked"
    counts = PAYLOAD["counts"]
    assert counts["total"] == len(PAYLOAD["vectors"]) == len(VECTORS)  # unique ids
    assert counts["accepted"] == len(ACCEPTED) and counts["rejected"] == len(REJECTED)
    by_category: dict[str, int] = {}
    for item in PAYLOAD["vectors"]:
        by_category[item["category"]] = by_category.get(item["category"], 0) + 1
        assert item["state"] in {"accepted", "rejected"}
    assert by_category == counts["by_category"]


def test_vector_file_pins_reference_source_sha256():
    for name, path in PINNED_SOURCES.items():
        recorded = PAYLOAD["sources"][name]["sha256"]
        assert hashlib.sha256(path.read_bytes()).hexdigest() == recorded, REGENERATE_HINT


@pytest.mark.parametrize("item", ACCEPTED, ids=lambda item: item["id"])
def test_accepted_vectors_replay_byte_exact(item):
    raw = expand(item["input"])
    assert len(raw) == item["input_byte_count"]
    if item["input"]["form"] == "literal":
        assert item["input"]["utf8_hex"] == raw.hex()  # text and hex agree
    encoded, digest = encoder.encode_source_bytes(raw)
    ast = parse_exact_json(raw)
    canonical = canonical_exact_json(ast)
    assert digest == hashlib.sha256(canonical).hexdigest() == item["sha256"]
    namespace = PAYLOAD["constants"]["namespaced_sha256_namespace"]
    assert exact_digest(ast, namespace=namespace) == item["sha256_namespaced"]
    if item.get("output_binding") == "sha256_only_size":
        # Oversized boundary vectors bind via digest over the expanded input.
        assert len(canonical) == item["canonical_byte_count"]
        assert "canonical" not in item and "encoded" not in item
        return
    assert canonical == bytes.fromhex(item["canonical"]["utf8_hex"])
    assert canonical == item["canonical"]["text"].encode("utf-8")
    assert encoded == item["encoded"]
    assert json.dumps(encoded, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":")) == item["encoded_canonical_text"]


@pytest.mark.parametrize("item", REJECTED, ids=lambda item: item["id"])
def test_rejected_vectors_fail_closed_with_recorded_codes(item):
    assert len(item["errors"]) == 1
    with pytest.raises(ProjectionError) as raised:
        encoder.encode_source_bytes(expand(item["input"]))
    assert raised.value.code == item["errors"][0]


def test_cross_vector_invariants_hold():
    invariants = PAYLOAD["cross_vector_invariants"]
    for first, second in invariants["sha256_must_differ"]:
        assert VECTORS[first]["sha256"] != VECTORS[second]["sha256"], (first, second)
    for first, second in invariants["canonical_must_match"]:
        assert VECTORS[first]["canonical"]["utf8_hex"] == VECTORS[second]["canonical"]["utf8_hex"]
    for first, second in invariants["encoded_must_differ"]:
        assert VECTORS[first]["encoded"] != VECTORS[second]["encoded"], (first, second)


def test_key_sort_order_is_codepoint_not_utf16():
    """The recorded non-BMP trap really diverges from UTF-16 code-unit order."""
    trap = VECTORS["sort_trap_ff21_vs_10000"]
    canonical = bytes.fromhex(trap["canonical"]["utf8_hex"]).decode("utf-8")
    assert canonical == '{"\uff21":2,"\U00010000":1}'  # codepoint: FF21 < 10000
    utf16_keys = sorted(["\U00010000", "\uff21"], key=lambda s: s.encode("utf-16-be"))
    assert utf16_keys == ["\U00010000", "\uff21"]  # UTF-16 order is the opposite


def test_number_vs_lookalike_encoding_stays_disjoint_from_token_dto_ambiguity():
    """E2 lock: the two sources encode differently even though the sealed
    core's token_dto collapses them to the same ambiguous shape."""
    from tire_api.device_ai_projection import token_dto

    number = VECTORS["disambig_number_5"]
    lookalike = VECTORS["disambig_lookalike_token_dto"]
    assert number["encoded"] != lookalike["encoded"]
    assert number["encoded"]["kind"] == "number"
    assert lookalike["encoded"]["kind"] == "structured"
    assert token_dto(parse_exact_json(expand(number["input"]))) == \
        token_dto(parse_exact_json(expand(lookalike["input"])))  # documented ambiguity
