/**
 * Unified closed-decoder fixtures replay (TS Host side) — decoder-spec 4.3-3.
 *
 * Replays .artifacts/device-ai50/specs/decoder-fixtures-a/fixtures.json through
 * the real Host decoder layers (generated by
 * apps/api/tests/generate_device_ai_decoder_fixtures.py; expected codes were
 * read from the four implementations, never guessed):
 *
 *   - message "prepare_body": assertDeviceAiPrepareBody (the same final gate
 *     buildDeviceAiPrepareBody runs before dispatch);
 *   - message "provider_consent": DeviceAiHostClient.submitStream's consent
 *     key-set assertion, which throws BEFORE any transport call (a mock
 *     transport is installed as a backstop anyway).
 *
 * Per-case expected.ts semantics (fixtures legend):
 *   "device_ai_host_invalid_argument" -> DeviceAiHostError fence code;
 *   "closed_fields_error"             -> plain programming Error whose message
 *                                        carries "closed DTO" (key-set assertion,
 *                                        not a fence code) — selftest convention;
 *   "accept"                          -> the TS runtime assert layer observes
 *                                        acceptance (registered divergence: the
 *                                        nested selector key-set duty is carried
 *                                        by the TS type system at build time);
 *   null                              -> accepted; UUID spellings additionally
 *                                        canonicalize to lowercase (M6).
 *
 * Run (packages/api-client): npm test (selftest + this file).
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { setApiTransport } from "../../src/index.ts";
import {
  DeviceAiHostClient,
  DeviceAiHostError,
  assertDeviceAiPrepareBody,
  canonicalDeviceAiUuid,
} from "../../src/device-ai-host.ts";

type ExpectedCode = "device_ai_host_invalid_argument" | "closed_fields_error" | "accept" | null;
interface FixtureCase {
  id: string;
  matrix_ref: string;
  message: "prepare_body" | "provider_consent";
  verdict: "accept" | "reject";
  payload: Record<string, unknown>;
  expected: { py: string | null; ts: ExpectedCode; rs: string | null; jv: string | null };
}
interface FixtureFile {
  schema: string;
  counts: { total: number; accept: number; reject: number; by_matrix: Record<string, number> };
  cases: FixtureCase[];
}

const FIXTURES = JSON.parse(readFileSync(fileURLToPath(
  new URL("../../../../.artifacts/device-ai50/specs/decoder-fixtures-a/fixtures.json", import.meta.url),
), "utf8")) as FixtureFile;

let passed = 0;
const failures: string[] = [];
const section = (name: string) => console.log(`\n== ${name} ==`);
const ok = (name: string, condition: boolean, detail = "") => {
  if (condition) { passed++; console.log(`  PASS ${name}`); }
  else { failures.push(`${name}${detail ? ` — ${detail}` : ""}`); console.log(`  FAIL ${name}${detail ? ` — ${detail}` : ""}`); }
};
const throwsHost = (name: string, fn: () => unknown, code: string) => {
  try { fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof DeviceAiHostError && error.code === code, `code=${(error as { code?: string }).code}`); }
};
/** Closed-field assertions fail as plain programming Errors (not fence codes). */
const throwsClosed = (name: string, fn: () => unknown): void => {
  try { fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof Error && /closed DTO/.test(error.message), String(error)); }
};
const throwsClosedAsync = async (name: string, fn: () => Promise<unknown>): Promise<void> => {
  try { await fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof Error && /closed DTO/.test(error.message), String(error)); }
};

function checkFileSelfConsistency(): void {
  section("fixtures file self-consistency");
  ok("schema is device-ai-decoder-fixtures@1", FIXTURES.schema === "device-ai-decoder-fixtures@1");
  const cases = FIXTURES.cases;
  ok("total count and unique ids", FIXTURES.counts.total === cases.length
    && new Set(cases.map(item => item.id)).size === cases.length);
  ok("accept/reject counts", FIXTURES.counts.accept === cases.filter(item => item.verdict === "accept").length
    && FIXTURES.counts.reject === cases.filter(item => item.verdict === "reject").length);
  const byMatrix: Record<string, number> = {};
  let shapeOk = true;
  for (const item of cases) {
    const ends = Object.keys(item.expected).sort();
    if (ends.join(",") !== "jv,py,rs,ts") shapeOk = false;
    if (item.verdict === "accept" && ends.some(end => item.expected[end as "ts"] !== null)) shapeOk = false;
    byMatrix[item.matrix_ref] = (byMatrix[item.matrix_ref] ?? 0) + 1;
  }
  ok("expected key set + accept cases carry all-null codes", shapeOk);
  ok("by_matrix distribution", JSON.stringify(byMatrix) === JSON.stringify(FIXTURES.counts.by_matrix));
}

async function replayPrepareBody(item: FixtureCase): Promise<void> {
  const expected = item.expected.ts;
  const body = item.payload as never;
  if (expected === null || expected === "accept") {
    try {
      assertDeviceAiPrepareBody(body);
      const label = expected === null ? "accepted" : "runtime assert layer observes acceptance (registered divergence)";
      ok(`${item.id} ${label}`, true);
      const receipt = item.payload.host_receipt_id;
      if (typeof receipt === "string") {
        ok(`${item.id} host_receipt_id canonicalized lowercase`, canonicalDeviceAiUuid(receipt) === receipt.toLowerCase());
      }
    } catch (error) {
      ok(`${item.id} ${expected === null ? "accepted" : "observed acceptance"}`, false, String(error));
    }
    return;
  }
  if (expected === "device_ai_host_invalid_argument") {
    throwsHost(`${item.id} fence code device_ai_host_invalid_argument`,
      () => assertDeviceAiPrepareBody(body), expected);
    return;
  }
  throwsClosed(`${item.id} closed key-set assertion`, () => assertDeviceAiPrepareBody(body));
}

async function replayProviderConsent(item: FixtureCase): Promise<void> {
  // The consent key-set assertion runs inside submitStream, before dispatch.
  const client = new DeviceAiHostClient();
  const submission = {
    pack_id: "pack-1", question: "P225 这条轮胎的历史参数如何解析？", prepare_id: "prep-1",
    host_receipt_id: "11111111-2222-4333-8444-555555555555",
    device_context_fingerprint: "03".repeat(32),
    provider_consent: item.payload,
  };
  const expected = item.expected.ts;
  if (expected === "device_ai_host_invalid_argument") {
    await (async () => {
      try { await client.submitStream(submission as never, "11111111-2222-4333-8444-555555555555"); ok(item.id, false, "no throw"); }
      catch (error) { ok(item.id, error instanceof DeviceAiHostError && error.code === expected, String(error)); }
    })();
    return;
  }
  await throwsClosedAsync(`${item.id} consent closed key-set assertion`, () =>
    client.submitStream(submission as never, "11111111-2222-4333-8444-555555555555"));
}

async function main(): Promise<void> {
  checkFileSelfConsistency();
  section("decoder fixtures replay (TS Host)");
  const restore = setApiTransport(async () => new Response(JSON.stringify({ detail: "unexpected" }), { status: 500 }));
  try {
    for (const item of FIXTURES.cases) {
      if (item.message === "prepare_body") await replayPrepareBody(item);
      else await replayProviderConsent(item);
    }
  } finally {
    restore();
  }
  console.log(`\ndecoder-fixtures: ${passed} passed, ${failures.length} failed`);
  if (failures.length) {
    for (const failure of failures) console.log(`  FAIL ${failure}`);
    process.exitCode = 1;
  }
}

await main();
