/**
 * device-ai Host SDK selftest (round 50, P1-3 host step 2).
 *
 * Repo copy (decoder-spec 4.3-2 item 4: TS coverage into CI; the .artifacts
 * original stays as round-50 evidence). Run (packages/api-client):
 *   npm test
 * i.e. node --experimental-transform-types \
 *   --import ./tests/device-ai/json-esm-hook.mjs \
 *   ./tests/device-ai/device-ai-host-selftest.mts
 *
 * Sections:
 *   A. Server DTO field-name parity (frozen lists manually transcribed from
 *      apps/api/tire_api/device_ai.py + ai_analysis.py AnalysisRequest).
 *   B. question trim-once + bare sha256 parity against Python reference
 *      digests (host-expected-fingerprints.json, generated by
 *      gen-expected-fingerprints.py over the sealed
 *      tire_api.device_ai_projection reference).
 *   C. selection_sha256 / device_context_fingerprint / local_preview_fingerprint
 *      parity with the same Python reference vectors (fingerprint-spec 2/3/4).
 *   D. device-ai-exact regression anchors from e1-canonical-vectors-a.json.
 *   E. computeLocalPreview over the SEALED projection vectors (P1-4b): four
 *      domains + frozen_decision_closure, projection_binding="recomputed"
 *      with projection_sha256 anchored to the sealed canonical shas, plus
 *      fail-closed cases (binding drift, member/receipt mismatch, consent
 *      gate, mode/kind mismatch).
 *   F. DeviceAiJournal: append/readAll/verify + tamper + chain break + the
 *      five fences (owner / generation / SHA / clock / session).
 *   G. DeviceAiHostClient over a mock transport: paths, Idempotency-Key,
 *      closed request bodies, error passthrough, response checks.
 *   H. resolveUnknownOutcome (N18): lookup-first, never resubmit.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { ApiError, setApiTransport } from "../../src/index.ts";
import {
  DeviceAiHostError,
  assertDeviceAiPrepareBody,
  assertDeviceAiPrepareSelector,
  buildDeviceAiPrepareBody,
  canonicalDeviceAiUuid,
  computeLocalPreview,
  deviceContextFingerprint,
  localPreviewFingerprint,
  normalizeQuestion,
  questionSha256,
  selectionSha256,
  trimOnceQuestion,
  resolveUnknownOutcome,
  DeviceAiHostClient,
  DeviceAiJournal,
  DEVICE_AI_PREPARE_REQUEST_FIELDS,
  DEVICE_AI_SUBMISSION_FIELDS,
  DEVICE_AI_PROVIDER_CONSENT_FIELDS,
  DEVICE_AI_ANALYSIS_REQUEST_FIELDS,
  type DeviceAiJournalStore,
  type DeviceAiPrepareSelectorWire,
  type DeviceAiSelectorWire,
  type DeviceAiOriginBindingWire,
  type DeviceAiProviderConsentBody,
} from "../../src/device-ai-host.ts";
import { deviceAiDigest, parseDeviceAiJson } from "../../src/device-ai-exact.ts";
import { DeviceAiProjectionPortError, type DeviceAiProjectionMode } from "../../src/device-ai-projection.ts";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const EXPECTED = JSON.parse(readFileSync(HERE + "host-expected-fingerprints.json", "utf8")) as {
  question_sha256: Record<string, string>;
  selection_sha256: string;
  device_context_fingerprint: string;
  local_preview_fingerprint: string;
};
const E1 = JSON.parse(readFileSync(HERE + "../../../../.artifacts/device-ai50/specs/e1-canonical-vectors-a.json", "utf8")) as {
  vectors: { id: string; input: { form: string; text?: string }; state: string; sha256?: string }[];
};

let passed = 0;
const failures: string[] = [];
const section = (name: string) => console.log(`\n== ${name} ==`);
const ok = (name: string, condition: boolean, detail = "") => {
  if (condition) { passed++; console.log(`  PASS ${name}`); }
  else { failures.push(`${name}${detail ? ` — ${detail}` : ""}`); console.log(`  FAIL ${name}${detail ? ` — ${detail}` : ""}`); }
};
const eq = (name: string, actual: unknown, expected: unknown) =>
  ok(name, JSON.stringify(actual) === JSON.stringify(expected), `actual=${JSON.stringify(actual)} expected=${JSON.stringify(expected)}`);
const throwsHost = (name: string, fn: () => unknown, code: string) => {
  try { fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof DeviceAiHostError && error.code === code, `code=${(error as { code?: string }).code}`); }
};
/** Closed-field assertions fail as plain programming Errors (not fence codes). */
const throwsClosed = (name: string, fn: () => unknown) => {
  try { fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof Error && /closed DTO/.test(error.message), String(error)); }
};
const throwsHostAsync = async (name: string, fn: () => Promise<unknown>, code: string) => {
  try { await fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof DeviceAiHostError && error.code === code, `code=${(error as { code?: string }).code}`); }
};
/** Projection-port closed codes surface verbatim (same strings the server returns). */
const throwsPortAsync = async (name: string, fn: () => Promise<unknown>, code: string) => {
  try { await fn(); ok(name, false, "no throw"); }
  catch (error) { ok(name, error instanceof DeviceAiProjectionPortError && error.code === code, `code=${(error as { code?: string }).code}`); }
};

// Shared mini inputs (must stay in lockstep with gen-expected-fingerprints.py).
const MK_A = "ab".repeat(32), MK_B = "cd".repeat(32);
const selA: DeviceAiTireSelectorWire = {
  kind: "tire", member_key: MK_A, document_id: null, record_index: null,
  reference: { kind: "tire", snapshot_id: "snap-1", variant_id: "var-1", verification_id: "ver-1" },
};
const selB: DeviceAiTireSelectorWire = {
  kind: "tire", member_key: MK_B, document_id: "doc-2", record_index: null,
  reference: { kind: "tire", snapshot_id: "snap-2", variant_id: "var-2", verification_id: "ver-2" },
};
const ORIGIN: DeviceAiOriginBindingWire = {
  expected_profile_id: "11111111-2222-4333-8444-555555555555",
  expected_owner_epoch: 1, slot_id: "slot-1", expected_generation: 2,
  package_id: "pkg-1", expected_sha256: "ef".repeat(32), expected_byte_count: 1234,
  owner_scope_id: "9a".repeat(32), package_schema: "offline-pack@2",
};
const QUESTION = "P225 这条轮胎的历史参数如何解析？";
const SOURCE_JSON = '{"source_id":"src-1","observed_at":"2026-01-01T00:00:00Z","verified_at":null,"verification_id":"ver-1","load_index_9007199254740993":9007199254740993,"pressure":0.1000000000000000001,"negative_zero":-0}';

// ===========================================================================
export async function main(): Promise<void> {
  await sectionA();
  sectionB();
  await sectionC();
  await sectionD();
  await sectionE();
  await sectionF();
  await sectionG();
  await sectionI();
  await sectionH();

  console.log(`\n==== ${passed} passed, ${failures.length} failed ====`);
  if (failures.length) {
    for (const failure of failures) console.log("FAILED:", failure);
    process.exitCode = 1;
  }
}

// ---------------------------------------------------------------------------
// A. Server DTO field parity.
// ---------------------------------------------------------------------------
async function sectionA(): Promise<void> {
  section("A. server DTO field parity");
  // Manually transcribed from apps/api/tire_api/device_ai.py (DeviceAIPrepareRequest,
  // DeviceSubmission, ProviderConsent) and ai_analysis.py (AnalysisRequest).
  const serverPrepare = ["package_id", "expected_sha256", "expected_byte_count", "expected_schema",
    "expected_owner_scope_id", "selectors", "projection_mode", "approved_closure",
    "expected_projection_sha256", "question_sha256", "host_receipt_id", "intent_id"];
  const serverSubmission = ["prepare_id", "host_receipt_id", "device_context_fingerprint", "provider_consent"];
  const serverConsent = ["expected_pack_fingerprint", "expected_device_context_fingerprint", "question_sha256",
    "provider", "model", "expected_provider_policy_fingerprint"];
  const serverAnalysis = ["pack_id", "question", "allow_external_processing", "device_submission"];
  eq("A1 prepare fields == server DeviceAIPrepareRequest", [...DEVICE_AI_PREPARE_REQUEST_FIELDS], serverPrepare);
  eq("A2 submission fields == server DeviceSubmission", [...DEVICE_AI_SUBMISSION_FIELDS], serverSubmission);
  eq("A3 consent fields == server ProviderConsent", [...DEVICE_AI_PROVIDER_CONSENT_FIELDS], serverConsent);
  eq("A4 analysis fields == server AnalysisRequest", [...DEVICE_AI_ANALYSIS_REQUEST_FIELDS], serverAnalysis);

  const validPrepare = {
    package_id: "pkg-1", expected_sha256: "ef".repeat(32), expected_byte_count: 1234,
    expected_schema: "offline-pack@2" as const, expected_owner_scope_id: "9a".repeat(32),
    selectors: [selA], projection_mode: "single_observation" as const, approved_closure: null,
    expected_projection_sha256: "99".repeat(32), question_sha256: "01".repeat(32),
    host_receipt_id: "11111111-2222-4333-8444-555555555555",
    intent_id: "11111111-2222-4333-8444-555555555555",
  };
  assertDeviceAiPrepareBody(validPrepare);
  ok("A5 valid prepare body passes closed assertion", true);
  throwsClosed("A6 extra field rejected (server extra=forbid would 422)", () => assertDeviceAiPrepareBody({ ...validPrepare, local_preview_fingerprint: "x".repeat(64) } as never));
  const missing = { ...validPrepare } as Partial<typeof validPrepare>;
  delete missing.question_sha256;
  throwsClosed("A7 missing required field rejected", () => assertDeviceAiPrepareBody(missing as never));
  // M6 (decoder-spec section 3): UUID negative family — non-UUID shapes and
  // non-canonical spellings (no-hyphen / version 0 / variant c) fail closed;
  // the uppercase/braced positives live in G3/H1.
  for (const bad of ["not-a-uuid", "9999aaaa0bbbb0cccc0dddd055555eee66666",
    "9999aaaa-bbbb-0ccc-8ddd-5555eee66666", "9999aaaa-bbbb-4ccc-cddd-5555eee66666",
    "9999aaaa bbbb 4ccc 8ddd 5555eee66666"]) {
    throwsHost(`A8 non-canonical UUID rejected (${bad.slice(0, 16)}…)`, () => canonicalDeviceAiUuid(bad), "device_ai_host_invalid_argument");
  }
}

// ---------------------------------------------------------------------------
// B. question trim-once + bare sha256 parity (Python reference digests).
// ---------------------------------------------------------------------------
function sectionB(): void {
  section("B. question trim-once + sha256 parity");
  eq("B1 strip both ends once", trimOnceQuestion("  历史问题  "), "历史问题");
  eq("B2 U+3000 and U+000B are whitespace (Python set)", trimOnceQuestion("　历史问题\v"), "历史问题");
  eq("B3 internal whitespace preserved", trimOnceQuestion("问题  内容"), "问题  内容");
  eq("B4 whole leading/trailing run stripped in one pass", trimOnceQuestion("   问题   内容   "), "问题   内容");
  // Pinned whitespace set evidence: U+001C IS Python whitespace (JS trim would
  // strip it too only in some engines; U+FEFF is NOT Python whitespace — a
  // naive String.prototype.trim() would strip it and break parity).
  eq("B5 U+001C stripped (Python set, beyond JS trim)", trimOnceQuestion("\x1c问题\x1c"), "问题");
  eq("B6 U+FEFF kept (not in Python set, differs from JS trim)", trimOnceQuestion("\ufeff问题"), "\ufeff问题");
  eq("B7 normalize passes codepoint min", normalizeQuestion("ab"), "ab");
  throwsHost("B8 one codepoint rejected", () => normalizeQuestion("a"), "device_ai_host_invalid_argument");
  eq("B9 2000 non-BMP codepoints pass (codepoint counting)", normalizeQuestion("𐀀".repeat(2000)), "𐀀".repeat(2000));
  throwsHost("B10 2001 codepoints rejected", () => normalizeQuestion("𐀀".repeat(2001)), "device_ai_host_invalid_argument");
  // UTF-16 vs codepoint: 2000 surrogate pairs are 4000 UTF-16 units.
  throwsHost("B11 1001 non-BMP pairs (2002 codepoints) rejected", () => normalizeQuestion("𐀀𐀀".repeat(1001)), "device_ai_host_invalid_argument");
}

// ---------------------------------------------------------------------------
// C. fingerprint parity (async).
// ---------------------------------------------------------------------------
async function sectionC(): Promise<void> {
  section("C. fingerprint parity vs Python reference");
  for (const [text, digest] of Object.entries(EXPECTED.question_sha256)) {
    const actual = await questionSha256(text);
    eq(`C-q ${text.slice(0, 12)}…`, actual, digest);
  }
  // NFKC must not be applied; lookalike and fullwidth pairs must differ.
  ok("C1 ligature digests differ (no NFKC)", (await questionSha256("ﬃ 轮胎历史")) !== (await questionSha256("ffi 轮胎历史")));
  ok("C2 fullwidth digests differ (no NFKC)", (await questionSha256("２０００ 年")) !== (await questionSha256("2000 年")));
  ok("C3 no JSON quoting wrapper", (await questionSha256("text")) !== (await questionSha256('"text"')));

  // selection_sha256: request order (B first) must not matter — spec sorts by member_key.
  eq("C4 selection_sha256 unordered == Python", await selectionSha256([selB, selA]), EXPECTED.selection_sha256);
  eq("C5 selection_sha256 ordered == Python", await selectionSha256([selA, selB]), EXPECTED.selection_sha256);
  await throwsHostAsync("C6 duplicate member_key rejected", () => selectionSha256([selA, selA]), "device_ai_host_invalid_argument");

  // device_context_fingerprint: numeric lexemes preserved through the AST.
  const contextHash = await deviceContextFingerprint({
    package_id: "pkg-1", package_schema: "offline-pack@2", package_sha256: "ef".repeat(32),
    projection_mode: "single_observation", projection_sha256: "99".repeat(32), selection_sha256: "01".repeat(32),
    receipt_sources: [{ selector: selA, selection_reason: "requested", source: parseDeviceAiJson(new TextEncoder().encode(SOURCE_JSON)) }],
    device_citations: [], domain_boundaries: [],
  });
  eq("C7 device_context_fingerprint == Python (lexemes 9007199254740993 / 0.1000000000000000001 / -0)", contextHash, EXPECTED.device_context_fingerprint);

  const previewHash = await localPreviewFingerprint({
    questionSha256Value: await questionSha256(QUESTION), includeContextIds: [],
    projectionMode: "single_observation", queryContext: null, origin: ORIGIN,
    selected: [selB], resolvedClosure: [selA], state: "ready", projectionSha256Value: null,
  });
  eq("C8 local_preview_fingerprint == Python", previewHash, EXPECTED.local_preview_fingerprint);
  const blockedHash = await localPreviewFingerprint({
    questionSha256Value: await questionSha256(QUESTION), includeContextIds: [],
    projectionMode: "single_observation", queryContext: null, origin: ORIGIN,
    selected: [selB], resolvedClosure: [selA], state: "blocked", projectionSha256Value: null,
  });
  ok("C9 blocked vs ready differ (state stays in the input)", blockedHash !== previewHash);
  // M4 (decoder-spec section 3): include_context_ids must stay EMPTY until the
  // frozen wire opens the archive-id intent channel; non-empty fails closed
  // before entering the fingerprint AST (computeLocalPreview routes through
  // the same gate).
  const questionHash = await questionSha256(QUESTION);
  await throwsHostAsync("C10 include_context_ids non-empty rejected (must be empty)", () => localPreviewFingerprint({
    questionSha256Value: questionHash, includeContextIds: ["archive-1"],
    projectionMode: "single_observation", queryContext: null, origin: ORIGIN,
    selected: [selB], resolvedClosure: [selA], state: "ready", projectionSha256Value: null,
  }), "device_ai_host_invalid_argument");
}

// ---------------------------------------------------------------------------
// D. device-ai-exact regression anchors from the frozen E1 vectors.
// ---------------------------------------------------------------------------
async function sectionD(): Promise<void> {
  section("D. E1 vector regression anchors");
  const anchors = ["scalar_top_text", "sample_token_9007199254740993", "sample_token_0_1000000000000000001", "escape_chinese_keys_and_text"];
  for (const id of anchors) {
    const vector = E1.vectors.find(item => item.id === id);
    if (!vector || vector.state !== "accepted" || !vector.sha256) { ok(`D ${id} present`, false, "vector missing"); continue; }
    const ast = parseDeviceAiJson(new TextEncoder().encode(vector.input.text!));
    eq(`D ${id}`, await deviceAiDigest(ast), vector.sha256);
  }
}

// ---------------------------------------------------------------------------
// E. computeLocalPreview over the SEALED projection vectors (P1-4b): four
// domains + frozen_decision_closure, projection re-computed on-device.
// ---------------------------------------------------------------------------
// The sealed vector corpus stays in .artifacts (read-only evidence); from the
// repo copy that is four levels up from this directory.
const VECTORS_DIR = HERE + "../../../../.artifacts/device-ai50/projection-vectors-a/";
const VECTOR_MANIFEST = JSON.parse(readFileSync(VECTORS_DIR + "manifest.json", "utf8")) as {
  source_core: { sha256: string };
  domain_vectors: { case: string; state: string; member_count?: number; input: { path: string }; expectation: { path: string } }[];
};
const PACKS_BY_SHA = new Map<string, Uint8Array>();
for (const name of ["legacy-pack.json", "nonempty-pack.json", "empty-pack.json"]) {
  const raw = new Uint8Array(readFileSync(VECTORS_DIR + "inputs/" + name));
  PACKS_BY_SHA.set(createHash("sha256").update(raw).digest("hex"), raw);
}
const sha256Hex = (bytes: Uint8Array): string => createHash("sha256").update(bytes).digest("hex");
const HASH64_RE = /^[0-9a-f]{64}$/;

interface LoadedCase {
  vector: { case: string; state: string; member_count?: number; input: { path: string }; expectation: { path: string } };
  input: {
    mode: DeviceAiProjectionMode;
    approved_closure: DeviceAiSelectorWire[] | null;
    binding: { package_id: string; owner_scope_id: string; sha256: string; byte_count: number; schema: "offline-pack@1" | "offline-pack@2" };
    selectors: DeviceAiSelectorWire[];
    max_projection_bytes: number;
    core_sha256: string;
  };
  expectation: { canonical_projection: { sha256: string; byte_count: number } | null; expected_error_code: string | null };
  bytes: Uint8Array;
}
function loadVectorCase(name: string): LoadedCase {
  const vector = VECTOR_MANIFEST.domain_vectors.find(item => item.case === name);
  if (!vector) throw new Error(`sealed vector missing: ${name}`);
  const input = JSON.parse(readFileSync(VECTORS_DIR + vector.input.path, "utf8")) as LoadedCase["input"];
  const expectation = JSON.parse(readFileSync(VECTORS_DIR + vector.expectation.path, "utf8")) as LoadedCase["expectation"];
  if (input.core_sha256 !== VECTOR_MANIFEST.source_core.sha256) throw new Error(`core sha drift on ${name}`);
  const bytes = PACKS_BY_SHA.get(input.binding.sha256);
  if (!bytes || bytes.byteLength !== input.binding.byte_count || sha256Hex(bytes) !== input.binding.sha256) {
    throw new Error(`sealed pack missing for ${name}`);
  }
  return { vector, input, expectation, bytes };
}
function vectorOrigin(input: LoadedCase["input"]): DeviceAiOriginBindingWire {
  return {
    expected_profile_id: ORIGIN.expected_profile_id, expected_owner_epoch: ORIGIN.expected_owner_epoch,
    slot_id: ORIGIN.slot_id, expected_generation: ORIGIN.expected_generation,
    package_id: input.binding.package_id, expected_sha256: input.binding.sha256,
    expected_byte_count: input.binding.byte_count, owner_scope_id: input.binding.owner_scope_id,
    package_schema: input.binding.schema,
  };
}

async function sectionE(): Promise<void> {
  section("E. computeLocalPreview over sealed vectors");

  // --- tire single_observation: the phase-A path, now with recomputed projection.
  const single = loadVectorCase("empty-tire-single");
  const singleOrigin = vectorOrigin(single.input);
  const summary = await computeLocalPreview(single.bytes, { question: `  ${QUESTION}  `, selectors: single.input.selectors, origin: singleOrigin });
  eq("E1 located member == sealed selector", summary.located_member_keys, single.input.selectors.map(item => item.member_key));
  eq("E2 package byte count", summary.package_byte_count, single.bytes.byteLength);
  eq("E3 package schema", summary.package_schema, single.input.binding.schema);
  eq("E4 question_sha256 (trim-once inside)", summary.question_sha256, EXPECTED.question_sha256[QUESTION]);
  eq("E5 selection_sha256 == SDK helper over requested closure", summary.selection_sha256, await selectionSha256(single.input.selectors));
  eq("E6 projection_binding recomputed (P1-4b)", summary.projection_binding, "recomputed");
  eq("E7 projection_sha256 == sealed canonical vector", summary.projection_sha256, single.expectation.canonical_projection!.sha256);
  eq("E8 projection byte count == sealed", summary.projection_byte_count, single.expectation.canonical_projection!.byte_count);
  eq("E9 resolved closure == requested (single mode)", summary.resolved_closure_member_keys, single.input.selectors.map(item => item.member_key));
  ok("E10 device_context_fingerprint is a local digest", HASH64_RE.test(summary.device_context_fingerprint));
  eq("E11 preview fingerprint self-consistent (recomputed sha inside, state ready)", summary.local_preview_fingerprint, await localPreviewFingerprint({
    questionSha256Value: await questionSha256(QUESTION), includeContextIds: [], projectionMode: "single_observation",
    queryContext: null, origin: singleOrigin, selected: single.input.selectors,
    resolvedClosure: single.input.selectors, state: "ready", projectionSha256Value: summary.projection_sha256,
  }));

  // --- frozen_decision_closure: no expansion in this vector + consent gate.
  const closure = loadVectorCase("empty-tire-closure");
  const closureSummary = await computeLocalPreview(closure.bytes, {
    question: QUESTION, selectors: closure.input.selectors, origin: vectorOrigin(closure.input), projectionMode: "frozen_decision_closure",
  });
  eq("E12 closure projection_sha256 == sealed vector", closureSummary.projection_sha256, closure.expectation.canonical_projection!.sha256);
  eq("E13 closure resolved closure member keys", closureSummary.resolved_closure_member_keys, closure.input.selectors.map(item => item.member_key));
  // An exact approved closure is accepted and changes nothing (core L744-749).
  const consented = await computeLocalPreview(closure.bytes, {
    question: QUESTION, selectors: closure.input.selectors, origin: vectorOrigin(closure.input),
    projectionMode: "frozen_decision_closure", approvedClosure: closure.input.selectors,
  });
  eq("E14 matching approved_closure accepted, same projection", consented.projection_sha256, closure.expectation.canonical_projection!.sha256);
  await throwsPortAsync("E15 empty approved_closure rejected (consent gate)", () => computeLocalPreview(closure.bytes, {
    question: QUESTION, selectors: closure.input.selectors, origin: vectorOrigin(closure.input),
    projectionMode: "frozen_decision_closure", approvedClosure: [],
  }), "device_ai_closure_consent_required");

  // --- vehicle / recall / recall_search domain dispatch, each anchored to its
  //     sealed canonical projection sha.
  for (const [name, mode] of [
    ["empty-vehicle-complete", "complete_observation"],
    ["empty-formal-recall-nonempty", "complete_formal_observation"],
    ["empty-formal-recall-empty", "complete_formal_observation"],
    ["empty-recall-search-empty", "candidate_page_context"],
  ] as const) {
    const domain = loadVectorCase(name);
    const domainSummary = await computeLocalPreview(domain.bytes, {
      question: QUESTION, selectors: domain.input.selectors, origin: vectorOrigin(domain.input), projectionMode: mode,
    });
    eq(`E16 ${name} projection_sha256 == sealed`, domainSummary.projection_sha256, domain.expectation.canonical_projection!.sha256);
    eq(`E17 ${name} projection_mode echoed`, domainSummary.projection_mode, mode);
    ok(`E18 ${name} context fingerprint differs from tire case`, domainSummary.device_context_fingerprint !== summary.device_context_fingerprint);
  }

  // --- test_event stays rejection-only, with the server's closed code.
  const restricted = loadVectorCase("empty-test-event-restricted");
  await throwsPortAsync("E19 test_event rejected device_ai_selected_restricted", () => computeLocalPreview(restricted.bytes, {
    question: QUESTION, selectors: restricted.input.selectors, origin: vectorOrigin(restricted.input), projectionMode: "complete_event_context",
  }), "device_ai_selected_restricted");

  // --- fail-closed paths (host fences first, then authoritative port codes).
  await throwsHostAsync("E20 sha mismatch fails closed", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: single.input.selectors, origin: { ...singleOrigin, expected_sha256: "ff".repeat(32) },
  }), "device_ai_host_package_mismatch");
  await throwsHostAsync("E21 byte count mismatch fails closed", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: single.input.selectors, origin: { ...singleOrigin, expected_byte_count: single.bytes.byteLength + 1 },
  }), "device_ai_host_package_mismatch");
  await throwsPortAsync("E22 unknown member -> authoritative port code", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: [{ ...single.input.selectors[0], member_key: "ee".repeat(32) }], origin: singleOrigin,
  }), "device_ai_member_missing");
  const foreignRef = { ...single.input.selectors[0], reference: { ...single.input.selectors[0].reference, snapshot_id: "00000000-0000-4000-8000-000000000000" } };
  await throwsPortAsync("E23 reference mismatch -> authoritative port code", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: [foreignRef as DeviceAiSelectorWire], origin: singleOrigin,
  }), "device_ai_receipt_mismatch");
  await throwsPortAsync("E24 duplicate selector rejected", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: [...single.input.selectors, ...single.input.selectors], origin: singleOrigin,
  }), "device_ai_selector_ambiguous");
  await throwsHostAsync("E25 empty selector list rejected", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: [], origin: singleOrigin,
  }), "device_ai_host_invalid_argument");
  await throwsHostAsync("E26 malformed question rejected", () => computeLocalPreview(single.bytes, {
    question: "a", selectors: single.input.selectors, origin: singleOrigin,
  }), "device_ai_host_invalid_argument");
  const vehicleCase = loadVectorCase("empty-vehicle-complete");
  await throwsPortAsync("E27 mode/kind mismatch (vehicle under single_observation)", () => computeLocalPreview(vehicleCase.bytes, {
    question: QUESTION, selectors: vehicleCase.input.selectors, origin: vectorOrigin(vehicleCase.input), projectionMode: "single_observation",
  }), "device_ai_projection_mode_unsupported");
  await throwsHostAsync("E28 unknown mode string rejected", () => computeLocalPreview(single.bytes, {
    question: QUESTION, selectors: single.input.selectors, origin: singleOrigin, projectionMode: "bogus" as DeviceAiProjectionMode,
  }), "device_ai_host_preview_unsupported");
}

// ---------------------------------------------------------------------------
// F. Journal: append / verify / tamper / five fences.
// ---------------------------------------------------------------------------
class MemoryStore implements DeviceAiJournalStore {
  blob: Uint8Array | null = null;
  async load(): Promise<Uint8Array | null> { return this.blob ? this.blob.slice() : null; }
  async save(blob: Uint8Array): Promise<void> { this.blob = blob.slice(); }
}

const jAad = (owner: string): Uint8Array => new TextEncoder().encode(JSON.stringify(["device-ai-journal@1", owner]));
async function unsealForTest(blob: Uint8Array, key: CryptoKey): Promise<{ wire: { schema: string; owner: string; generation: number; iv_hex: string; ciphertext_base64: string }; entries: unknown[] }> {
  const wire = JSON.parse(new TextDecoder().decode(blob)) as { iv_hex: string; ciphertext_base64: string };
  const iv = Uint8Array.from(wire.iv_hex.match(/../g)!, hex => Number.parseInt(hex, 16));
  const ciphertext = Uint8Array.from(atob(wire.ciphertext_base64), char => char.charCodeAt(0));
  const plaintext = new Uint8Array(await globalThis.crypto.subtle.decrypt({ name: "AES-GCM", iv, additionalData: jAad(wire.owner) }, key, ciphertext));
  return { wire: wire as never, entries: (JSON.parse(new TextDecoder().decode(plaintext)) as { entries: unknown[] }).entries };
}
async function resealForTest(wire: { schema: string; owner: string; generation: number; iv_hex: string; ciphertext_base64: string }, entries: unknown[], key: CryptoKey): Promise<Uint8Array> {
  const iv = globalThis.crypto.getRandomValues(new Uint8Array(12));
  const plaintext = new TextEncoder().encode(JSON.stringify({ entries }));
  const ciphertext = await globalThis.crypto.subtle.encrypt({ name: "AES-GCM", iv, additionalData: jAad(wire.owner) }, key, plaintext);
  return new TextEncoder().encode(JSON.stringify({ ...wire, iv_hex: Array.from(iv, b => b.toString(16).padStart(2, "0")).join(""), ciphertext_base64: btoa(String.fromCharCode(...new Uint8Array(ciphertext))) }));
}

async function sectionF(): Promise<void> {
  section("F. journal append / verify / tamper / five fences");
  const key = await globalThis.crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
  const otherKey = await globalThis.crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
  const store = new MemoryStore();
  let clock = 0;
  const journal = new DeviceAiJournal({
    owner: "profile-1", generation: 1, sessionId: "session-1", key, store,
    monotonicNow: () => clock += 10, wallNow: () => "2026-10-02T00:00:00Z",
  });

  const empty = await journal.verifyIntegrity();
  ok("F1 empty journal verifies", empty.ok && empty.length === 0);

  const e1 = await journal.append({ type: "preview_shown", intent_id: "i-1", local_preview_fingerprint: "aa".repeat(32), question_sha256: "bb".repeat(32), package_sha256: "cc".repeat(32) });
  const e2 = await journal.append({ type: "decision_made", intent_id: "i-1", decision: "allow", local_preview_fingerprint: "aa".repeat(32) });
  const e3 = await journal.append({ type: "claim_submitted", intent_id: "i-1", prepare_id: "prep-1", analysis_key: "11111111-2222-4333-8444-555555555555", question_sha256: "bb".repeat(32) });
  eq("F2 sequence numbering", [e1.sequence, e2.sequence, e3.sequence], [1, 2, 3]);
  ok("F3 genesis prev", e1.prev_sha256 === "0".repeat(64));
  ok("F4 chained prev", e2.prev_sha256 === e1.entry_sha256 && e3.prev_sha256 === e2.entry_sha256);
  ok("F5 owner/generation/session stamped", e3.owner === "profile-1" && e3.generation === 1 && e3.session_id === "session-1");
  ok("F6 monotonic clock stamped", e1.clock === 10 && e2.clock === 20 && e3.clock === 30);

  const readBack = await journal.readAll();
  eq("F7 readAll preserves entries", readBack.length, 3);
  readBack[0].event.type = "failure_observed"; // mutate the returned copy only
  const again = await journal.readAll();
  eq("F8 readAll returns clones (stored copy untouched)", again[0].event.type, "preview_shown");

  const verified = await journal.verifyIntegrity();
  ok("F10 intact journal verifies clean", verified.ok && verified.length === 3 && verified.cross_session_entries.length === 0);

  // Fence 3 — tamper with entry content (entry_sha256 kept stale).
  {
    const { wire, entries } = await unsealForTest(store.blob!, key);
    (entries[1] as { event: { decision: string } }).event.decision = "deny";
    store.blob = await resealForTest(wire, entries, key);
    const tampered = await journal.verifyIntegrity();
    ok("F11 tampered entry detected (SHA fence)", !tampered.ok && tampered.violations.some(v => v.code === "device_ai_host_journal_entry_tampered" && v.sequence === 2));
    await throwsHostAsync("F12 readAll rejects tampered chain", () => journal.readAll(), "device_ai_host_journal_entry_tampered");
    (entries[1] as { event: { decision: string } }).event.decision = "allow";
    store.blob = await resealForTest(wire, entries, key);
    ok("F13 restored journal verifies again", (await journal.verifyIntegrity()).ok);
  }

  // Fence 3 — break the chain link.
  {
    const { wire, entries } = await unsealForTest(store.blob!, key);
    (entries[2] as { prev_sha256: string }).prev_sha256 = "ee".repeat(32);
    store.blob = await resealForTest(wire, entries, key);
    const broken = await journal.verifyIntegrity();
    ok("F14 broken chain detected", !broken.ok && broken.violations.some(v => v.code === "device_ai_host_journal_chain_broken" && v.sequence === 3));
    (entries[2] as { prev_sha256: string }).prev_sha256 = (entries[1] as { entry_sha256: string }).entry_sha256;
    store.blob = await resealForTest(wire, entries, key);
  }

  // Fence 4 — clock regression at write time.
  clock = 5;
  await throwsHostAsync("F15 append with regressed clock rejected", () => journal.append({ type: "failure_observed", intent_id: "i-1", stage: "submit", code: "api_network_unavailable" }), "device_ai_host_journal_clock_regression");
  clock = 40;
  const e4 = await journal.append({ type: "failure_observed", intent_id: "i-1", stage: "submit", code: "api_network_unavailable" });
  eq("F16 append resumes after clock restored", e4.sequence, 4);

  // Fence 4 — reordered entries (older clock appended after newer) detected on read.
  {
    const { wire, entries } = await unsealForTest(store.blob!, key);
    const reordered = [...entries];
    const last = reordered.pop()!;
    reordered.unshift(last); // sequence 4 (clock 40) before sequence 1 (clock 10)
    store.blob = await resealForTest(wire, reordered, key);
    const check = await journal.verifyIntegrity();
    ok("F17 clock regression in stored order detected", !check.ok && check.violations.some(v => v.code === "device_ai_host_journal_clock_regression"));
    store.blob = await resealForTest(wire, entries, key);
  }

  // Fence 1 — wrong owner.
  const wrongOwner = new DeviceAiJournal({ owner: "profile-2", generation: 1, sessionId: "session-1", key, store, monotonicNow: () => clock += 10 });
  const ownerCheck = await wrongOwner.verifyIntegrity();
  ok("F18 owner fence (header + AAD)", !ownerCheck.ok && ownerCheck.violations[0]?.code === "device_ai_host_journal_owner_mismatch");
  await throwsHostAsync("F19 readAll under wrong owner rejected", () => wrongOwner.readAll(), "device_ai_host_journal_owner_mismatch");

  // Fence 2 — stale generation after a rebuild.
  const staleGeneration = new DeviceAiJournal({ owner: "profile-1", generation: 2, sessionId: "session-1", key, store, monotonicNow: () => clock += 10 });
  const generationCheck = await staleGeneration.verifyIntegrity();
  ok("F20 generation fence voids old blob", !generationCheck.ok && generationCheck.violations[0]?.code === "device_ai_host_journal_generation_mismatch");

  // Wrong key: AES-GCM AAD/authentication fails => corrupt.
  const wrongKey = new DeviceAiJournal({ owner: "profile-1", generation: 1, sessionId: "session-1", key: otherKey, store, monotonicNow: () => clock += 10 });
  const keyCheck = await wrongKey.verifyIntegrity();
  ok("F21 wrong key fails decryption (corrupt)", !keyCheck.ok && keyCheck.violations[0]?.code === "device_ai_host_journal_corrupt");

  // Fence 5 — session binding.
  const nextSession = new DeviceAiJournal({ owner: "profile-1", generation: 1, sessionId: "session-2", key, store, monotonicNow: () => clock += 10 });
  const cross = await nextSession.verifyIntegrity();
  ok("F22 recovery read allowed across sessions (structure ok)", cross.ok);
  eq("F23 cross-session entries recorded", cross.cross_session_entries.length, 4);
  const freshEntries = await nextSession.readAll();
  throwsHost("F24 assertSameSession on real cross-session entries", () => nextSession.assertSameSession(freshEntries), "device_ai_host_journal_session_mismatch");
  const appended = await nextSession.append({ type: "failure_observed", intent_id: null, stage: "recover", code: "none" });
  eq("F25 new entries stamp the current session", appended.session_id, "session-2");
}

// ---------------------------------------------------------------------------
// G. Host client over a mock transport.
// ---------------------------------------------------------------------------
function streamDetailFixture(): Record<string, unknown> {
  return {
    schema: "ai-streams@1", scope: "session",
    execution: { state: "accepted", terminal: false, deadline_at: "2026-10-02T12:30:00Z", last_event_at: null, projection_only: false },
    cursor: "cursor-1", server_time: "2026-10-02T12:00:00Z",
    analysis: {
      id: "req-1", pack_id: "pack-1", question: "问题", provider: "openai_responses", model: "m-1",
      created_at: "2026-10-02T12:00:00Z", completed_at: null, state: "pending", reserved_tokens: 100,
      usage: null, error_code: null, answer: null,
    },
    draft_claims: [], draft_uncertainty: null, replayed: false,
  };
}

async function sectionG(): Promise<void> {
  section("G. host client paths / headers / bodies / errors");
  const calls: { path: string; method?: string; headers: Headers; body?: string }[] = [];
  let responder: ((path: string) => Response) | null = null;
  const restore = setApiTransport(async (path, init) => {
    calls.push({ path, method: init.method, headers: new Headers(init.headers), body: typeof init.body === "string" ? init.body : undefined });
    return responder!(path);
  });
  const client = new DeviceAiHostClient();
  const key = "9999AAAA-BBBB-4CCC-8DDD-5555EEE66666"; // uppercase spelling on purpose
  const canonicalKey = "9999aaaa-bbbb-4ccc-8ddd-5555eee66666";
  const prepareBody = {
    package_id: "pkg-1", expected_sha256: "ef".repeat(32), expected_byte_count: 1234,
    expected_schema: "offline-pack@2" as const, expected_owner_scope_id: "9a".repeat(32),
    selectors: [selA], projection_mode: "single_observation" as const, approved_closure: null,
    expected_projection_sha256: "99".repeat(32), question_sha256: "01".repeat(32),
    host_receipt_id: "11111111-2222-4333-8444-555555555555",
    intent_id: "22222222-3333-4444-8555-666666666666",
  };
  const prepareView = {
    id: "prep-1", created_at: "2026-10-02T12:00:00Z", expires_at: "2026-10-02T12:30:00Z", expired: false,
    idempotency_key: canonicalKey, host_receipt_id: prepareBody.host_receipt_id, intent_id: prepareBody.intent_id,
    pack_id: "pack-1", offline_pack_id: "pkg-1", question_sha256: prepareBody.question_sha256,
    selection_sha256: "02".repeat(32), projection_sha256: "99".repeat(32), projection_byte_count: 1000,
    device_context_fingerprint: "03".repeat(32), request_hash: "04".repeat(32), contract: {}, pack: {},
    replayed: false, provider_preview: { model: { provider: "openai_responses" } },
  };

  try {
    responder = () => new Response(JSON.stringify(prepareView), { status: 201, headers: { "content-type": "application/json" } });
    const view = await client.prepare(prepareBody, key);
    ok("G1 prepare returns checked view", view.id === "prep-1" && view.replayed === false);
    eq("G2 prepare method+path", [calls.at(-1)!.method, calls.at(-1)!.path], ["POST", "/v1/ai/device-evidence-packs"]);
    eq("G3 Idempotency-Key canonicalized", calls.at(-1)!.headers.get("Idempotency-Key"), canonicalKey);
    const body = JSON.parse(calls.at(-1)!.body!);
    eq("G4 prepare body closed field set", Object.keys(body).sort(), [...DEVICE_AI_PREPARE_REQUEST_FIELDS].sort());
    eq("G5 receipt UUID canonicalized in body", body.host_receipt_id, "11111111-2222-4333-8444-555555555555");

    responder = () => {
      const replayView = { ...prepareView } as Partial<typeof prepareView>;
      delete replayView.provider_preview; // server replay branch omits it
      return new Response(JSON.stringify({ ...replayView, replayed: true }), { status: 200 });
    };
    const replayed = await client.prepare(prepareBody, canonicalKey);
    ok("G6 replay response passes with provider_preview omitted", replayed.replayed === true && replayed.provider_preview === undefined);

    responder = () => new Response(JSON.stringify({ ...prepareView, expires_at: "not-a-date" }), { status: 200 });
    let threw = false;
    try { await client.prepare(prepareBody, key); } catch { threw = true; }
    ok("G7 malformed view rejected", threw);

    // D6/M7 alignment (decoder-spec 2.5 + section 3): view times must carry a
    // timezone offset (RFC 3339). The server emits Python isoformat() with
    // "+00:00" and optional fractional seconds — that shape must pass; naive
    // and date-only spellings Date.parse would accept must now fail closed.
    responder = () => new Response(JSON.stringify({ ...prepareView, expires_at: "2026-10-02T12:30:00.123456+00:00" }), { status: 200 });
    const offsetView = await client.prepare(prepareBody, key);
    ok("G23 view accepts server isoformat offset spelling", offsetView.id === "prep-1");
    responder = () => new Response(JSON.stringify({ ...prepareView, expires_at: "2026-10-02T12:30:00" }), { status: 200 });
    threw = false;
    try { await client.prepare(prepareBody, key); } catch { threw = true; }
    ok("G24 naive view time (no timezone offset) rejected", threw);
    responder = () => new Response(JSON.stringify({ ...prepareView, expires_at: "2026-10-02" }), { status: 200 });
    threw = false;
    try { await client.prepare(prepareBody, key); } catch { threw = true; }
    ok("G25 date-only view time rejected", threw);

    responder = () => new Response(JSON.stringify({ detail: { code: "device_ai_prepare_conflict", message: "已绑定既有准备记录" } }), { status: 409 });
    try { await client.prepare({ ...prepareBody, intent_id: "33333333-3333-4444-8555-666666666666" }, key); ok("G8 409 throws", false); }
    catch (error) {
      ok("G8 409 closed code passthrough", error instanceof ApiError && error.status === 409 && error.code === "device_ai_prepare_conflict", String(error));
    }

    responder = () => new Response(JSON.stringify(prepareView), { status: 200 });
    await client.lookupPrepare(key);
    eq("G9 lookup path", calls.at(-1)!.path, `/v1/ai/device-evidence-packs/lookup?mode=history&idempotency_key=${canonicalKey}`);
    eq("G10 lookup is GET (fetch default)", calls.at(-1)!.method ?? "GET", "GET");
    await client.readPrepare("prep-1");
    eq("G11 read path", calls.at(-1)!.path, "/v1/ai/device-evidence-packs/prep-1?mode=history");

    responder = () => new Response(JSON.stringify({ detail: "未找到本会话的设备 AI 准备记录" }), { status: 404 });
    try { await client.lookupPrepare(key); ok("G12 404 throws", false); }
    catch (error) { ok("G12 404 passthrough for resolveUnknownOutcome", error instanceof ApiError && error.status === 404); }

    // submitStream: body shape + normalization.
    responder = () => new Response(JSON.stringify(streamDetailFixture()), { status: 202, headers: { "content-type": "application/json" } });
    const consent: DeviceAiProviderConsentBody = {
      expected_pack_fingerprint: "aa".repeat(32), expected_device_context_fingerprint: "03".repeat(32),
      question_sha256: EXPECTED.question_sha256[QUESTION], provider: "openai_responses", model: "m-1",
      expected_provider_policy_fingerprint: "05".repeat(32),
    };
    const acceptance = await client.submitStream({
      pack_id: "pack-1", question: `\u3000${QUESTION}\u3000`, prepare_id: "prep-1",
      host_receipt_id: "11111111-2222-4333-8444-555555555555", device_context_fingerprint: "03".repeat(32), provider_consent: consent,
    }, key);
    ok("G13 submit acceptance checked (replayed flag)", acceptance.replayed === false);
    const submitBody = JSON.parse(calls.at(-1)!.body!);
    eq("G14 AnalysisRequest closed field set", Object.keys(submitBody).sort(), [...DEVICE_AI_ANALYSIS_REQUEST_FIELDS].sort());
    eq("G15 device_submission closed field set", Object.keys(submitBody.device_submission).sort(), [...DEVICE_AI_SUBMISSION_FIELDS].sort());
    eq("G16 provider_consent closed field set", Object.keys(submitBody.device_submission.provider_consent).sort(), [...DEVICE_AI_PROVIDER_CONSENT_FIELDS].sort());
    ok("G17 allow_external_processing literal true", submitBody.allow_external_processing === true);
    eq("G18 question normalized exactly once (trim-once)", submitBody.question, QUESTION);
    eq("G19 submit Idempotency-Key canonical", calls.at(-1)!.headers.get("Idempotency-Key"), canonicalKey);

    responder = () => new Response(JSON.stringify({ ...streamDetailFixture(), replayed: undefined }), { status: 202 });
    threw = false;
    try { await client.submitStream({ pack_id: "pack-1", question: QUESTION, prepare_id: "prep-1", host_receipt_id: "11111111-2222-4333-8444-555555555555", device_context_fingerprint: "03".repeat(32), provider_consent: consent }, key); }
    catch { threw = true; }
    ok("G20 acceptance without replayed flag rejected", threw);

    responder = () => new Response(JSON.stringify(streamDetailFixture()), { status: 200 });
    await client.lookupAttempt(key);
    eq("G21 attempt lookup path (frozen analysis key)", calls.at(-1)!.path, `/v1/ai/analysis-streams/lookup?mode=history&idempotency_key=${canonicalKey}`);

    responder = () => new Response(JSON.stringify({ detail: { code: "device_ai_consent_mismatch", message: "六元组不一致" } }), { status: 409 });
    try { await client.submitStream({ pack_id: "pack-1", question: QUESTION, prepare_id: "prep-1", host_receipt_id: "11111111-2222-4333-8444-555555555555", device_context_fingerprint: "03".repeat(32), provider_consent: { ...consent, model: "other" } }, key); ok("G22 submit 409 throws", false); }
    catch (error) { ok("G22 submit 409 closed code passthrough", error instanceof ApiError && error.status === 409 && error.code === "device_ai_consent_mismatch"); }
  } finally {
    restore();
  }
}

// ---------------------------------------------------------------------------
// I. Four-domain prepare-body assembly (P1-4c): computeLocalPreview ->
// buildDeviceAiPrepareBody over the SEALED vectors; expected_projection_
// sha256 comes from the on-device recomputation (== sealed canonical sha).
// ---------------------------------------------------------------------------
async function sectionI(): Promise<void> {
  section("I. four-domain prepare body assembly");
  const uuid = "11111111-2222-4333-8444-555555555555";
  const prepareSelectors = (selectors: DeviceAiSelectorWire[]): DeviceAiPrepareSelectorWire[] =>
    selectors as unknown as DeviceAiPrepareSelectorWire[];

  // --- every open domain: preview -> closed body, projection sha == sealed.
  const domainCases = [
    ["empty-tire-single", "single_observation"],
    ["empty-vehicle-complete", "complete_observation"],
    ["empty-formal-recall-nonempty", "complete_formal_observation"],
    ["empty-formal-recall-empty", "complete_formal_observation"],
    ["empty-recall-search-empty", "candidate_page_context"],
  ] as const;
  const singleCase = loadVectorCase("empty-tire-single");
  const singleOrigin = vectorOrigin(singleCase.input);
  const singleSelectors = prepareSelectors(singleCase.input.selectors);
  const singleSummary = await computeLocalPreview(singleCase.bytes, {
    question: QUESTION, selectors: singleSelectors, origin: singleOrigin, projectionMode: "single_observation",
  });
  for (const [name, mode] of domainCases) {
    const domainCase = loadVectorCase(name);
    const origin = vectorOrigin(domainCase.input);
    const selectors = prepareSelectors(domainCase.input.selectors);
    const summary = await computeLocalPreview(domainCase.bytes, {
      question: QUESTION, selectors, origin, projectionMode: mode,
    });
    const body = buildDeviceAiPrepareBody({ origin, preview: summary, selectors, approvedClosure: null, hostReceiptId: uuid, intentId: uuid });
    eq(`I1 ${name} projection_mode echoed`, body.projection_mode, mode);
    eq(`I2 ${name} expected_projection_sha256 == sealed recompute`, body.expected_projection_sha256, domainCase.expectation.canonical_projection!.sha256);
    eq(`I3 ${name} approved_closure null outside closure mode`, body.approved_closure, null);
    eq(`I4 ${name} origin/question echo verbatim`,
      [body.question_sha256, body.package_id, body.expected_sha256, body.expected_byte_count, body.expected_schema, body.expected_owner_scope_id],
      [summary.question_sha256, origin.package_id, origin.expected_sha256, origin.expected_byte_count, origin.package_schema, origin.owner_scope_id]);
    eq(`I5 ${name} selectors carried in request order`, body.selectors.map(item => item.member_key), selectors.map(item => item.member_key));
  }

  // --- frozen_decision_closure: approved closure carried verbatim.
  const closureCase = loadVectorCase("empty-tire-closure");
  const closureOrigin = vectorOrigin(closureCase.input);
  const closureSelectors = prepareSelectors(closureCase.input.selectors);
  const closureSummary = await computeLocalPreview(closureCase.bytes, {
    question: QUESTION, selectors: closureSelectors, origin: closureOrigin,
    projectionMode: "frozen_decision_closure", approvedClosure: closureSelectors,
  });
  const closureBody = buildDeviceAiPrepareBody({
    origin: closureOrigin, preview: closureSummary, selectors: closureSelectors,
    approvedClosure: closureSelectors, hostReceiptId: uuid, intentId: uuid,
  });
  eq("I6 closure approved_closure == resolved closure keys", [...closureBody.approved_closure!].map(item => item.member_key).sort(),
    [...closureSummary.resolved_closure_member_keys].sort());
  eq("I7 closure expected_projection_sha256 == sealed", closureBody.expected_projection_sha256, closureCase.expectation.canonical_projection!.sha256);
  eq("I8 closure body mode", closureBody.projection_mode, "frozen_decision_closure");

  // --- buildDeviceAiPrepareBody fail-closed paths (host fences).
  throwsHost("I9 approved_closure forbidden in single mode", () => buildDeviceAiPrepareBody({
    origin: singleOrigin, preview: singleSummary, selectors: singleSelectors,
    approvedClosure: singleSelectors, hostReceiptId: uuid, intentId: uuid,
  }), "device_ai_host_invalid_argument");
  throwsHost("I10 closure mode requires an approved closure", () => buildDeviceAiPrepareBody({
    origin: closureOrigin, preview: closureSummary, selectors: closureSelectors,
    approvedClosure: null, hostReceiptId: uuid, intentId: uuid,
  }), "device_ai_host_invalid_argument");
  const driftedClosure = [...closureSelectors, { ...closureSelectors[0], member_key: "ee".repeat(32) }] as unknown as DeviceAiPrepareSelectorWire[];
  throwsHost("I11 approved closure drifting from resolved closure rejected", () => buildDeviceAiPrepareBody({
    origin: closureOrigin, preview: closureSummary, selectors: closureSelectors,
    approvedClosure: driftedClosure, hostReceiptId: uuid, intentId: uuid,
  }), "device_ai_host_invalid_argument");
  throwsHost("I12 located-key echo mismatch rejected", () => buildDeviceAiPrepareBody({
    origin: singleOrigin, preview: singleSummary,
    selectors: [{ ...singleSelectors[0], member_key: "ee".repeat(32) }] as unknown as DeviceAiPrepareSelectorWire[],
    approvedClosure: null, hostReceiptId: uuid, intentId: uuid,
  }), "device_ai_host_invalid_argument");
  throwsHost("I13 package echo drift rejected", () => buildDeviceAiPrepareBody({
    origin: { ...singleOrigin, expected_sha256: "ff".repeat(32) }, preview: singleSummary, selectors: singleSelectors,
    approvedClosure: null, hostReceiptId: uuid, intentId: uuid,
  }), "device_ai_host_package_mismatch");

  // --- closed-body semantics mirroring the server DTO validator (P1-4a).
  const validPrepare = {
    package_id: "pkg-1", expected_sha256: "ef".repeat(32), expected_byte_count: 1234,
    expected_schema: "offline-pack@2" as const, expected_owner_scope_id: "9a".repeat(32),
    selectors: [selA], projection_mode: "single_observation" as const, approved_closure: null,
    expected_projection_sha256: "99".repeat(32), question_sha256: "01".repeat(32),
    host_receipt_id: uuid, intent_id: uuid,
  };
  const vehicleSelector: DeviceAiPrepareSelectorWire = {
    kind: "vehicle", member_key: "0a".repeat(32), document_id: null, record_index: null,
    reference: { kind: "vehicle", snapshot_id: "snap-v", verification_id: "ver-v" },
  };
  const vehiclePrepare = {
    ...validPrepare, selectors: [vehicleSelector], projection_mode: "complete_observation" as const,
  };
  assertDeviceAiPrepareBody(vehiclePrepare);
  ok("I14 vehicle-domain body passes the closed assertion", true);
  const recallSearchPrepare = {
    ...validPrepare, selectors: [{
      kind: "recall_search", member_key: "0b".repeat(32), document_id: "doc-rs", record_index: 2,
      reference: { kind: "recall_search", snapshot_id: "snap-rs", verification_id: "ver-rs" },
    } as DeviceAiPrepareSelectorWire], projection_mode: "candidate_page_context" as const,
  };
  assertDeviceAiPrepareBody(recallSearchPrepare);
  ok("I15 recall_search record selector accepted (record-carrying domain)", true);
  throwsHost("I16 test_event selector stays closed (N27)", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "complete_event_context" as never,
    selectors: [{ kind: "test_event", member_key: "0c".repeat(32), document_id: null, record_index: null,
      reference: { kind: "test_event", event_id: "evt-1", event_revision: 1 } } as never],
  }), "device_ai_host_invalid_argument");
  throwsHost("I17 complete_event_context is not a prepare mode", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "complete_event_context" as never,
  }), "device_ai_host_invalid_argument");
  throwsHost("I18 tire selector with record_index rejected (whole-observation domain)", () => assertDeviceAiPrepareBody({
    ...validPrepare, selectors: [{ ...selA, document_id: "doc-1", record_index: 3 }],
  }), "device_ai_host_invalid_argument");
  throwsHost("I19 vehicle selector with record_index rejected", () => assertDeviceAiPrepareBody({
    ...vehiclePrepare, selectors: [{ ...vehicleSelector, document_id: "doc-v", record_index: 0 }],
  }), "device_ai_host_invalid_argument");
  throwsHost("I20 record_index without document_id rejected (recall)", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "complete_formal_observation" as const,
    selectors: [{ kind: "recall", member_key: "0d".repeat(32), document_id: null, record_index: 1,
      reference: { kind: "recall", snapshot_id: "snap-r", recall_revision_id: null, verification_id: "ver-r" } } as DeviceAiPrepareSelectorWire],
  }), "device_ai_host_invalid_argument");
  throwsHost("I21 selector capacity 6 exceeded", () => assertDeviceAiPrepareBody({
    ...validPrepare, selectors: Array.from({ length: 7 }, (_, index) =>
      ({ ...selA, member_key: String(index).repeat(64) })),
  }), "device_ai_host_invalid_argument");
  throwsHost("I22 duplicate member keys rejected", () => assertDeviceAiPrepareBody({
    ...validPrepare, selectors: [selA, { ...selA, reference: selA.reference }],
  }), "device_ai_host_invalid_argument");
  throwsHost("I23 approved_closure capacity 6 exceeded in closure mode", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "frozen_decision_closure" as const,
    approved_closure: Array.from({ length: 7 }, (_, index) => ({ ...selA, member_key: String(index).repeat(64) })),
  }), "device_ai_host_invalid_argument");
  throwsHost("I24 approved_closure items carry the same closed selector shape", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "frozen_decision_closure" as const,
    approved_closure: [{ ...selA, record_index: 2, document_id: "doc-x" }],
  }), "device_ai_host_invalid_argument");
  throwsHost("I25 per-selector prepare assertion is exported and closed", () =>
    assertDeviceAiPrepareSelector({ ...selA, record_index: 1, document_id: "doc-x" }), "device_ai_host_invalid_argument");
  // M8 (decoder-spec section 3): hash64 negative family — uppercase and
  // wrong-length spellings fail the closed-body assertion like the server 422.
  throwsHost("I26 uppercase hash64 rejected (expected_sha256)", () => assertDeviceAiPrepareBody({
    ...validPrepare, expected_sha256: "EF".repeat(32),
  }), "device_ai_host_invalid_argument");
  throwsHost("I27 short hash64 rejected (selector member_key)", () => assertDeviceAiPrepareBody({
    ...validPrepare, selectors: [{ ...selA, member_key: "a".repeat(63) }],
  }), "device_ai_host_invalid_argument");
  // D5 (decoder-spec 2.6): approved_closure member_key uniqueness at the
  // decoder layer (Rust parity), independent of the builder equality gate.
  throwsHost("I28 approved_closure duplicate member_key rejected", () => assertDeviceAiPrepareBody({
    ...validPrepare, projection_mode: "frozen_decision_closure" as const,
    approved_closure: [selA, { ...selB, member_key: selA.member_key }],
  }), "device_ai_host_invalid_argument");
  // D4 (decoder-spec 4.3-2): expected_byte_count above the 8 MiB package cap
  // (object_store.py MAX_OBJECT_BYTES) now fails the Host assert like the
  // server 422, instead of riding the old 1..2^53-1 slack.
  throwsHost("I29 expected_byte_count above the 8MiB package cap rejected (D4)", () => assertDeviceAiPrepareBody({
    ...validPrepare, expected_byte_count: 8_388_609,
  }), "device_ai_host_invalid_argument");
}

// ---------------------------------------------------------------------------
// H. resolveUnknownOutcome (N18).
// ---------------------------------------------------------------------------
async function sectionH(): Promise<void> {
  section("H. resolveUnknownOutcome lookup-first");
  const client = new DeviceAiHostClient();
  const analysisKey = "12345678-1234-4234-8345-123456789abc";
  let lookupCount = 0;
  let submitCount = 0;
  const restore = setApiTransport(async (path, init) => {
    if (path.startsWith("/v1/ai/analysis-streams/lookup")) { lookupCount++; return new Response(JSON.stringify(streamDetailFixture()), { status: 200 }); }
    if (path === "/v1/ai/analysis-streams" && init.method === "POST") { submitCount++; return new Response("{}", { status: 202 }); }
    return new Response(JSON.stringify({ detail: "unexpected" }), { status: 500 });
  });
  try {
    const resolved = await resolveUnknownOutcome(client, { analysisKey: analysisKey.toUpperCase() });
    ok("H1 hit returns resolved reference", resolved.kind === "resolved" && "detail" in resolved && resolved.detail.analysis.id === "req-1");
    eq("H2 exactly one lookup, zero submits", [lookupCount, submitCount], [1, 0]);
  } finally { restore(); }

  const notFound = setApiTransport(async () => new Response(JSON.stringify({ detail: "未找到" }), { status: 404 }));
  try {
    const noJournal = await resolveUnknownOutcome(client, { analysisKey });
    ok("H3 miss without journal => fresh decision allowed", noJournal.kind === "not_submitted");

    const key = await globalThis.crypto.subtle.generateKey({ name: "AES-GCM", length: 256 }, false, ["encrypt", "decrypt"]);
    const store = new MemoryStore();
    let clock = 0;
    const journal = new DeviceAiJournal({ owner: "profile-1", generation: 1, sessionId: "session-1", key, store, monotonicNow: () => clock += 10 });
    const emptyResult = await resolveUnknownOutcome(client, { analysisKey, journal });
    ok("H4 miss + empty journal => not_submitted", emptyResult.kind === "not_submitted");

    await journal.append({ type: "claim_submitted", intent_id: "intent-1", prepare_id: "prep-1", analysis_key: analysisKey, question_sha256: "bb".repeat(32) });
    const localClaim = await resolveUnknownOutcome(client, { analysisKey, journal, intentId: "intent-1" });
    ok("H5 miss + local claim => same-key-same-body user decision only",
      localClaim.kind === "unknown_local_claim" && localClaim.resubmission === "same_key_same_body_user_decision_only");
    eq("H6 no automatic resubmit happened", submitCount, 0);

    const otherIntent = await resolveUnknownOutcome(client, { analysisKey, journal, intentId: "intent-other" });
    ok("H7 claim filtered by intent id", otherIntent.kind === "not_submitted");

    const nextSession = new DeviceAiJournal({ owner: "profile-1", generation: 1, sessionId: "session-2", key, store, monotonicNow: () => clock += 10 });
    const cross = await resolveUnknownOutcome(client, { analysisKey, journal: nextSession, intentId: "intent-1" });
    ok("H8 cross-session claim never replays (fence 5)", cross.kind === "cross_session_replay_blocked");

    // Tamper the stored blob: integrity failure surfaces without resubmission.
    const { wire, entries } = await unsealForTest(store.blob!, key);
    (entries[0] as { event: { analysis_key: string } }).event.analysis_key = "forged";
    store.blob = await resealForTest(wire, entries, key);
    const integrity = await resolveUnknownOutcome(client, { analysisKey, journal });
    ok("H9 tampered journal => integrity failure surfaced", integrity.kind === "journal_integrity_failed" && integrity.violations.length > 0);
    eq("H10 still zero submits", submitCount, 0);
  } finally { notFound(); }
}

await main();
