"""Export the API runtime's Unicode rules without reading data or invoking services.

The JSON table is shared by device criteria. Android receives the same table as
generated Java constants so no package body, asset loader or network is needed
to validate a query. --check verifies the frozen outputs without rewriting them.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import unicodedata

ROOT = Path(__file__).resolve().parents[1]
UNICODE_VERSION = "15.0.0"
JSON_PATH = ROOT / "packages/domain-types/src/query-filter-unicode.json"
JAVA_PATH = ROOT / "apps/mobile/android/app/src/main/java/org/taiji/tireintelligence/mobile/OfflineFilterUnicode.java"


def table() -> dict:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise RuntimeError(f"Expected Unicode {UNICODE_VERSION}; got {unicodedata.unidata_version}")
    folds, digits, whitespace, ranges = {}, {}, [], []
    range_start = None
    for codepoint in range(0x110000):
        char = chr(codepoint)
        folded = char.casefold()
        if folded != char:
            folds[str(codepoint)] = folded
        if unicodedata.category(char) == "Nd":
            digits[str(codepoint)] = unicodedata.decimal(char)
        if char.isspace():
            whitespace.append(codepoint)
        category_c = unicodedata.category(char).startswith("C")
        if category_c and range_start is None:
            range_start = codepoint
        elif not category_c and range_start is not None:
            ranges.append([range_start, codepoint - 1])
            range_start = None
    if range_start is not None:
        ranges.append([range_start, 0x10FFFF])
    return {
        "schema": "tire-query-unicode@1", "unicode_version": UNICODE_VERSION,
        "casefold_map": folds, "category_c_ranges": ranges,
        "whitespace_codepoints": whitespace, "decimal_digit_map": digits,
    }


def java_array(name: str, values: list, java_type: str = "int") -> str:
    encoded = [json.dumps(value, ensure_ascii=True) for value in values]
    lines = ["        " + ", ".join(encoded[i:i + 12]) for i in range(0, len(encoded), 12)]
    return f"    private static {java_type}[] {name}() {{ return new {java_type}[] {{\n" + ",\n".join(lines) + "\n    }; }\n"


def java_source(data: dict) -> str:
    fold_keys = [int(key) for key in data["casefold_map"]]
    digit_keys = [int(key) for key in data["decimal_digit_map"]]
    ranges = [number for pair in data["category_c_ranges"] for number in pair]
    return """package org.taiji.tireintelligence.mobile;

import java.text.Normalizer;
import java.util.Arrays;

/** Generated by scripts/generate_query_filter_unicode.py. Do not edit tables. */
final class OfflineFilterUnicode {
    static final String VERSION = "15.0.0";
    private static final int[] CASE_KEYS = caseKeys();
    private static final String[] CASE_VALUES = caseValues();
    private static final int[] CATEGORY_C = categoryRanges();
    private static final int[] WHITESPACE = whitespace();
    private static final int[] DIGIT_KEYS = digitKeys();
    private static final int[] DIGIT_VALUES = digitValues();

    static boolean categoryC(int codepoint) {
        int lo = 0, hi = CATEGORY_C.length / 2 - 1;
        while (lo <= hi) {
            int mid = (lo + hi) >>> 1;
            if (codepoint < CATEGORY_C[mid * 2]) hi = mid - 1;
            else if (codepoint > CATEGORY_C[mid * 2 + 1]) lo = mid + 1;
            else return true;
        }
        return false;
    }
    static boolean isWhitespace(int codepoint) {
        return Arrays.binarySearch(WHITESPACE, codepoint) >= 0;
    }
    static int decimalDigit(int codepoint) {
        int at = Arrays.binarySearch(DIGIT_KEYS, codepoint);
        return at < 0 ? -1 : DIGIT_VALUES[at];
    }
    static String fold(String value) {
        StringBuilder result = new StringBuilder();
        value.codePoints().forEach(codepoint -> {
            int at = Arrays.binarySearch(CASE_KEYS, codepoint);
            if (at < 0) result.appendCodePoint(codepoint);
            else result.append(CASE_VALUES[at]);
        });
        return result.toString();
    }
    static String text(Object value) {
        if (!(value instanceof String)) throw new IllegalArgumentException("text_type");
        String input = (String) value;
        if (input.codePointCount(0, input.length()) > 512 || input.codePoints().anyMatch(OfflineFilterUnicode::categoryC))
            throw new IllegalArgumentException("text_bounds");
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFKC);
        StringBuilder collapsed = new StringBuilder();
        boolean pendingSpace = false;
        for (int offset = 0; offset < normalized.length();) {
            int codepoint = normalized.codePointAt(offset);
            offset += Character.charCount(codepoint);
            if (isWhitespace(codepoint)) { pendingSpace = collapsed.length() > 0; continue; }
            if (pendingSpace) collapsed.append(' ');
            collapsed.appendCodePoint(codepoint);
            pendingSpace = false;
        }
        String result = fold(collapsed.toString());
        int count = result.codePointCount(0, result.length());
        if (count == 0 || count > 512) throw new IllegalArgumentException("text_bounds");
        return result;
    }
    static boolean blank(String value) {
        return value.codePoints().allMatch(OfflineFilterUnicode::isWhitespace);
    }
""" + "\n".join([
        java_array("caseKeys", fold_keys),
        java_array("caseValues", list(data["casefold_map"].values()), "String"),
        java_array("categoryRanges", ranges),
        java_array("whitespace", data["whitespace_codepoints"]),
        java_array("digitKeys", digit_keys),
        java_array("digitValues", list(data["decimal_digit_map"].values())),
    ]) + "}\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = table()
    outputs = {
        JSON_PATH: json.dumps(data, ensure_ascii=True, indent=2) + "\n",
        JAVA_PATH: java_source(data),
    }
    for path, source in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != source:
                raise SystemExit(f"Generated Unicode data differs: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(source, encoding="utf-8", newline="\n")
    print(json.dumps({"schema": data["schema"], "unicode_version": data["unicode_version"],
                      "casefold_entries": len(data["casefold_map"]),
                      "category_c_ranges": len(data["category_c_ranges"]),
                      "decimal_digits": len(data["decimal_digit_map"]), "checked": args.check}))


if __name__ == "__main__":
    main()
