"""Round47 isolated real-browser IndexedDB and Workbench tests. All API routes are synthetic."""
from __future__ import annotations
import argparse, hashlib, json, subprocess, sys, time
from pathlib import Path
from urllib.parse import urlsplit
ROOT=Path(__file__).resolve().parents[1]

def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--web',default='http://127.0.0.1:3003');parser.add_argument('--output',type=Path,required=True);parser.add_argument('--owner-reset-only',action='store_true');args=parser.parse_args()
    assert args.web=='http://127.0.0.1:3003'
    output=args.output.resolve();assert output.is_relative_to((ROOT/'.artifacts/local-fallback').resolve());output.mkdir(parents=True,exist_ok=False)
    descriptor=json.loads((ROOT/'.artifacts/of46-wire-v2/valid-descriptor.json').read_text(encoding='utf-8'))
    raw=(ROOT/'.artifacts/of46-wire-v2/valid-envelope.json').read_text(encoding='utf-8');env=json.loads(raw)
    tire=next(member for member in env['members'] if member['reference']['kind']=='tire');model=tire['payload']['variant']['model'];size=tire['payload']['variant']['size'];source=tire['source']['source_id']
    report={'status':'running','normal_database_used':False,'real_source_or_model_calls':0,'checks':[],'geometry':[],'requests':[],'page_errors':[],'blocked_external':[]}
    files=['packages/api-client/src/index.ts','apps/web/components/browser-offline-store.ts','apps/web/components/local-fallback-values.ts','apps/web/components/local-fallback-controller.ts','apps/web/components/local-fallback-panel.tsx','apps/web/components/workbench.tsx','apps/web/components/source-status.tsx','apps/web/app/globals.css']
    report['sha256']={name:hashlib.sha256((ROOT/name).read_bytes()).hexdigest() for name in files}
    def save(): (output/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    def checked(name):report['checks'].append(name);save();print(json.dumps({'check':name}),flush=True)
    controls={'mode':'ready','source_generation':1,'source_state':'enabled','can_fetch':True}
    def route_handler(route):
        url=urlsplit(route.request.url)
        if url.netloc!=urlsplit(args.web).netloc:report['blocked_external'].append(url.hostname);route.abort();return
        if not url.path.startswith('/api/'):route.continue_();return
        path=url.path[4:];report['requests'].append({'path':path,'method':route.request.method,'mode':controls['mode']})
        if path=='/v1/source-settings' and controls['mode'] in ['network','http500','http403']:
            if controls['mode']=='network':route.abort('connectionfailed')
            else:route.fulfill(status=int(controls['mode'][4:]),json={'detail':'synthetic failure'})
            return
        setting={'scope':'local_workspace','source_id':source,'name':'合成轮胎来源','region':'US','target_kind':'tire','source_class':'official','homepage':'https://fixture.example','description':'synthetic','supported_models':[model], 'registered_status':'ready','environment_disabled':False,'management':{'state':controls['source_state'],'notes':'','access_generation':controls['source_generation'],'revision':controls['source_generation'],'event_id':None,'operator':None,'reason':None,'changed_at':None},'effective_status':'ready' if controls['source_state']=='enabled' else 'paused','can_fetch':controls['source_state']=='enabled' and controls['can_fetch'],'blockers':[],'fingerprint':'f'*64,'notice':'合成测试'}
        if path=='/health':data={'status':'ok','database':'ok','service':'synthetic'}
        elif path=='/v1/sources':data={'sources':[{'id':source,'name':'合成轮胎来源','region':'US','source_class':'official','status':'ready','target_kind':'tire','homepage':'https://fixture.example','description':'synthetic','supported_models':[model],'source_setting':setting}]}
        elif path=='/v1/source-settings':data={'scope':'local_workspace','items':[setting],'total':1,'notice':'synthetic'}
        elif path=='/v1/tire-query-filters':data={'version':'tire-query-filters@1','max_conditions':16,'fields':[{'key':'xl','label':'XL','type':'boolean','operators':['eq'],'options':[{'value':True,'label':'是'}]}]}
        elif path=='/v1/watchlists':data={'items':[]}
        elif path.endswith('/live-query'):
            data={'query_id':'88888888-8888-4888-8888-888888888888','source_id':source,'data_state':'consent_required' if controls['mode']=='source_timeout' else 'source_unavailable','reason':'upstream_timeout' if controls['mode']=='source_timeout' else 'source_fetch_failed','variants':[],'provenance':[],'conflicts':[],'selection':{'filters':[],'source_count':None,'matched_count':None,'excluded_count':None,'undetermined_count':None}}
        else:route.fulfill(status=404,json={'detail':'synthetic route unavailable'});return
        route.fulfill(status=200,json=data)
    sys.path.insert(0,str(ROOT/'.artifacts/browser-qa/python'))
    from playwright.sync_api import sync_playwright, expect
    module=subprocess.check_output(['node','--input-type=module','-e','import {offlineModuleUrl} from "./scripts/load_offline_typescript.mjs";process.stdout.write(await offlineModuleUrl(new URL("./apps/web/components/browser-offline-store.ts", "file:///"+process.cwd().replaceAll("\\\\","/")+"/")));'],cwd=ROOT,text=True,encoding='utf-8')
    browser=context=None
    try:
      with sync_playwright() as pw:
        browser=pw.chromium.launch(executable_path='C:/Program Files/Google/Chrome/Application/chrome.exe',headless=True)
        context=browser.new_context(viewport={'width':1440,'height':1000},service_workers='block');context.route('**/*',route_handler)
        page=context.new_page();page.set_default_timeout(30000);page.on('pageerror',lambda e:report['page_errors'].append(str(e)[:200]));page.goto(args.web,wait_until='networkidle')
        page.evaluate('async url=>{window.offlineQA=await import(url)}',module)
        slot=page.evaluate('''async ({descriptor,raw})=>{const fetch=window.fetch;window.fetch=async url=>String(url).includes('/download')?new Response(raw,{headers:{'content-type':'application/json','content-length':String(new TextEncoder().encode(raw).length),'x-content-sha256':descriptor.sha256}}):new Response(JSON.stringify(descriptor),{headers:{'content-type':'application/json'}});try{return await offlineQA.browserOfflineStorage.install({package_id:descriptor.id,expected_sha256:descriptor.sha256,expected_byte_count:descriptor.byte_count,approved_plan_fingerprint:descriptor.plan_fingerprint,slot_id:crypto.randomUUID(),expected_generation:0,allow_device_storage:true})}finally{window.fetch=fetch}}''',{'descriptor':descriptor,'raw':raw})
        page.evaluate('''()=>{window.payloadReads=0;const decrypt=crypto.subtle.decrypt.bind(crypto.subtle);crypto.subtle.decrypt=function(algorithm,...args){if(new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"'))window.payloadReads++;return decrypt(algorithm,...args)}}''')
        page.locator('.model-field select').select_option(model);page.locator('.size-field input').fill(size)
        def query():page.locator('.query-submit').click()
        def panel():return page.locator('.local-fallback-panel')
        controls['mode']='http500';query();expect(page.locator('.source-result')).to_contain_text('synthetic failure');expect(panel()).to_have_count(0)
        controls['mode']='http403';query();expect(page.locator('.source-result')).to_contain_text('synthetic failure');expect(panel()).to_have_count(0)
        controls['mode']='ready';query();expect(page.locator('.source-result')).to_contain_text('source_fetch_failed');expect(panel()).to_have_count(0)
        checked('HTTP500/403 and generic source_fetch_failed cannot authorize device fallback')
        controls['mode']='network';query();expect(panel()).to_have_count(1);expect(panel().get_by_role('button',name='允许本次读取设备历史')).to_be_enabled();assert page.evaluate('payloadReads')==0
        panel().get_by_role('button',name='拒绝本次设备回退').click();expect(panel()).to_contain_text('已拒绝本次设备回退');assert page.evaluate('payloadReads')==0
        checked('Directory fetch rejection prompts only after known enabled metadata; prompt and deny decrypt zero package payloads')
        query();expect(panel().get_by_role('button',name='允许本次读取设备历史')).to_be_enabled();panel().get_by_role('button',name='允许本次读取设备历史').click();expect(panel().locator('.local-fallback-member')).to_have_count(1);expect(panel()).to_contain_text(size)
        assert page.evaluate('payloadReads')==1;assert panel().get_by_role('button',name='AI 分析').count()==0;assert panel().get_by_role('button',name='加入比较').count()==0
        expect(panel().get_by_text('整包历史字段上下文（可能含其他来源/回执）',exact=True)).to_be_visible()
        checked('Allow consumes once and shows exact original member with isolated whole-package context and no online action buttons')
        if args.owner_reset_only:
            before=page.evaluate('async ()=>({status:await offlineQA.browserOfflineStorage.status(),payloadReads})')
            page.evaluate('''async ()=>{window.ownerResetEvents=0;window.resetFocusEvents=0;window.addEventListener('tire-offline-owner-changed',()=>window.ownerResetEvents++);window.addEventListener('focus',()=>window.resetFocusEvents++);await offlineQA.resetBrowserOfflineOwner()}''')
            expect(panel().locator('.local-fallback-member')).to_have_count(0);expect(panel().locator('.local-fallback-result')).to_have_count(0);expect(panel()).to_contain_text('归属');expect(panel().get_by_role('button',name='允许本次读取设备历史')).to_have_count(0)
            after=page.evaluate('async ()=>({status:await offlineQA.browserOfflineStorage.status(),list:await offlineQA.browserOfflineStorage.list(),payloadReads,events:ownerResetEvents,focusEvents:resetFocusEvents})')
            assert after['status']['owner_epoch']==before['status']['owner_epoch']+1 and after['payloadReads']==before['payloadReads'] and after['events']==1 and after['focusEvents']==0
            assert all(item['locked'] and item['previous_owner'] for item in after['list']['items'])
            checked('Same-page real IndexedDB owner reset emits exactly one event, immediately clears consumed private UI without focus and refreshes metadata without payload reads')
            for width,theme in [(1440,'light'),(390,'dark')]:
                page.set_viewport_size({'width':width,'height':1000});page.evaluate('(theme)=>document.querySelector(".app-shell").dataset.theme=theme',theme);panel().scroll_into_view_if_needed();page.screenshot(path=str(output/f'owner-reset-{width}-{theme}.png'))
            page.evaluate('''()=>{window.originalFallbackFetch=window.fetch;window.fetch=(url,init)=>String(url).includes('/source-settings')?new Promise((_resolve,reject)=>{window.failLateDirectory=()=>reject(new TypeError('synthetic network failure after owner reset'))}):window.originalFallbackFetch(url,init)}''')
            query();page.wait_for_function('typeof window.failLateDirectory === "function"');page.evaluate('''async()=>{await offlineQA.resetBrowserOfflineOwner();window.fetch=window.originalFallbackFetch;window.failLateDirectory()}''');page.wait_for_timeout(200);expect(panel()).to_have_count(0);checked('Owner-reset generation blocks a delayed directory transport failure from creating a new-device offer')
            page.locator('.size-field input').fill('999/10R99');query();expect(page.locator('.source-result')).to_contain_text('当前未能连接本机 API');expect(panel()).to_have_count(0);checked('Malformed tyre size plus actual directory fetch rejection never creates device consent UI')
            base=json.loads((ROOT/'.artifacts/local-fallback/browser-b/report.json').read_text(encoding='utf-8'))
            report['scope']='owner_reset_event_targeted_after_full_browser_b';report['base_report']='.artifacts/local-fallback/browser-b/report.json';report['changed_source_since_base']=[name for name,digest in report['sha256'].items() if base['sha256'].get(name)!=digest]
            assert sorted(report['changed_source_since_base'])==sorted(['apps/web/components/browser-offline-store.ts','apps/web/components/local-fallback-panel.tsx','apps/web/components/workbench.tsx','apps/web/components/local-fallback-values.ts'])
            report['owner_reset']={'before_epoch':before['status']['owner_epoch'],'after_epoch':after['status']['owner_epoch'],'events':after['events'],'focus_events':after['focusEvents'],'payload_reads_before':before['payloadReads'],'payload_reads_after':after['payloadReads']};report['status']='passed';save();context.close();browser.close();browser=None;return
        for width,theme in [(1440,'light'),(390,'dark')]:
            page.set_viewport_size({'width':width,'height':1000});page.evaluate('(theme)=>document.querySelector(".app-shell").dataset.theme=theme',theme)
            panel().scroll_into_view_if_needed();geometry=panel().evaluate('node=>({width:innerWidth,document:document.documentElement.scrollWidth,left:node.getBoundingClientRect().left,right:node.getBoundingClientRect().right,scroll:node.scrollWidth,client:node.clientWidth})');assert geometry['document']<=width and geometry['scroll']<=geometry['client']+1 and geometry['left']>=-1 and geometry['right']<=width+1;report['geometry'].append(geometry);page.screenshot(path=str(output/f'panel-{width}-{theme}.png'))
        page.locator('.size-field input').fill('265/40R20');expect(panel()).to_have_count(0);query();panel().get_by_role('button',name='允许本次读取设备历史').click();expect(panel()).to_contain_text('没有与本次来源、型号及尺寸完全匹配');assert panel().locator('.local-fallback-member').count()==0
        checked('Query edit invalidates prior result; R vs ZR is an explicit selected-package zero-match')
        page.locator('.size-field input').fill(size);controls['mode']='source_timeout';query();expect(panel()).to_have_count(1);expect(panel()).to_contain_text('本次来源核验返回网络中断或超时')
        controls['can_fetch']=False;page.evaluate('window.dispatchEvent(new Event("focus"))');expect(panel()).to_have_count(0)
        controls['can_fetch']=True;page.evaluate('window.dispatchEvent(new Event("focus"))');page.wait_for_timeout(250);query();expect(panel()).to_have_count(1)
        checked('A successfully observed parser/can_fetch pause revokes even without management generation change')
        controls['source_generation']=2;controls['source_state']='paused';page.evaluate('window.dispatchEvent(new Event("focus"))');expect(panel()).to_have_count(0)
        checked('Formal timeout also prompts; source permission generation change removes pending device offer')
        capacity=context.new_page();capacity.goto(args.web,wait_until='networkidle');capacity.evaluate('async url=>{window.offlineQA=await import(url)}',module)
        make_grant='''async ({slot,source,model,size})=>{const s=offlineQA.browserOfflineStorage,owner=await s.status(),request={intent:{schema:'device-fallback-intent@1',attempt_id:crypto.randomUUID(),query_fingerprint:'c'.repeat(64),source_id:source,source_access_generation:1,query:{model,size},filters:[],failure:{scope:'api_transport',reason:'api_timeout',query_id:null}},slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:owner.profile_id,expected_owner_epoch:owner.owner_epoch,decision:'allow'};return {request,grant:await s.decideFallback(request)}}'''
        consume_code='''async value=>{try{await offlineQA.browserOfflineStorage.consumeFallback({grant_id:value.grant.id,intent:value.request.intent});return 'unexpected_success'}catch(e){return e.code}}'''
        own=page.evaluate(make_grant,{'slot':slot,'source':source,'model':model,'size':size});assert capacity.evaluate(consume_code,own)=='OFFLINE_FALLBACK_USED';page.evaluate('async value=>offlineQA.browserOfflineStorage.revokeFallback({grant_id:value.grant.id})',own)
        lost=capacity.evaluate(make_grant,{'slot':slot,'source':source,'model':model,'size':size});capacity.reload(wait_until='networkidle');capacity.evaluate('async url=>{window.offlineQA=await import(url)}',module);assert capacity.evaluate(consume_code,lost)=='OFFLINE_FALLBACK_USED';checked('Grant from another page or before page reload cannot be consumed')
        capacity_result=capacity.evaluate('''async ({slot,source,model,size})=>{const s=offlineQA.browserOfflineStorage,owner=await s.status();let first;for(let n=0;n<1024;n++){const req={intent:{schema:'device-fallback-intent@1',attempt_id:crypto.randomUUID(),query_fingerprint:'b'.repeat(64),source_id:source,source_access_generation:1,query:{model,size},filters:[],failure:{scope:'api_transport',reason:'api_timeout',query_id:null}},slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:owner.profile_id,expected_owner_epoch:owner.owner_epoch,decision:'deny'};if(!first)first=req;await s.decideFallback(req);}let duplicate,full;try{await s.decideFallback(first)}catch(e){duplicate=e.code}try{await s.decideFallback({...first,intent:{...first.intent,attempt_id:crypto.randomUUID()}})}catch(e){full=e.code}return {duplicate,full}}''',{'slot':slot,'source':source,'model':model,'size':size})
        assert capacity_result=={'duplicate':'OFFLINE_FALLBACK_USED','full':'OFFLINE_FALLBACK_CAPACITY'};capacity.close();checked('Real IndexedDB records 1024 terminal decisions without eviction; oldest attempt remains used and new attempt fails capacity')
        controls['mode']='network';controls['source_state']='enabled';controls['can_fetch']=True
        cold_context=browser.new_context(viewport={'width':1440,'height':1000},service_workers='block');cold_context.route('**/*',route_handler);cold=cold_context.new_page();cold.goto(args.web,wait_until='networkidle');cold.locator('.model-field select').select_option(model);cold.locator('.size-field input').fill(size);expect(cold.locator('.query-submit')).to_be_disabled();expect(cold.locator('.local-fallback-panel')).to_have_count(0);cold.get_by_role('button',name='设备离线资料库',exact=True).first.click();expect(cold.get_by_role('dialog',name='设备离线资料库',exact=True)).to_be_visible();cold_context.close();checked('Unknown cold-start directory cannot authorize query fallback; independent device library remains accessible')
        host=page.evaluate('''async ({slot,source,model,size})=>{
          const s=offlineQA.browserOfflineStorage,status=await s.status(),checks=[];
          const request=(decision='allow')=>({intent:{schema:'device-fallback-intent@1',attempt_id:crypto.randomUUID(),query_fingerprint:'a'.repeat(64),source_id:source,source_access_generation:1,query:{model,size},filters:[],failure:{scope:'api_transport',reason:'api_network_unavailable',query_id:null}},slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:status.profile_id,expected_owner_epoch:status.owner_epoch,decision});
          const reject=async(promise,code)=>{try{await promise;throw Error('unexpected success '+code)}catch(e){if(e.code!==code)throw e}};
          let r=request('deny');await s.decideFallback(r);await reject(s.decideFallback({...r,decision:'allow'}),'OFFLINE_FALLBACK_USED');checks.push('deny cannot be upgraded for same attempt');
          r=request();let g=await s.decideFallback(r);let value=await s.consumeFallback({grant_id:g.id,intent:r.intent});if(value.members.length!==1)throw Error('match');await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');await reject(s.decideFallback(r),'OFFLINE_FALLBACK_USED');checks.push('consume and decide never replay');
          r=request();g=await s.decideFallback(r);const double=await Promise.allSettled([s.consumeFallback({grant_id:g.id,intent:r.intent}),s.consumeFallback({grant_id:g.id,intent:r.intent})]);if(double.filter(x=>x.status==='fulfilled').length!==1||double.find(x=>x.status==='rejected').reason.code!=='OFFLINE_FALLBACK_USED')throw Error('concurrent consume');checks.push('concurrent same-grant consume returns exactly one result');
          r=request();g=await s.decideFallback(r);const changed=structuredClone(r.intent);changed.query.model='other';await reject(s.consumeFallback({grant_id:g.id,intent:changed}),'OFFLINE_FALLBACK_MISMATCH');await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');checks.push('fingerprint alone cannot mask structured mismatch and failed consume burns grant');
          r=request();g=await s.decideFallback(r);await s.revokeFallback({grant_id:g.id});await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');await reject(s.decideFallback(r),'OFFLINE_FALLBACK_USED');checks.push('revocation terminal');
          r=request();g=await s.decideFallback(r);const now=Date.now;Date.now=()=>now()+301000;try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_EXPIRED')}finally{Date.now=now}checks.push('wall expiry');
          r=request();g=await s.decideFallback(r);const mono=performance.now.bind(performance);Object.defineProperty(performance,'now',{configurable:true,value:()=>mono()+301000});Date.now=()=>Date.parse(g.decided_at)+1000;try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_EXPIRED')}finally{delete performance.now;Date.now=now}checks.push('monotonic expiry while wall stays within TTL');
          r=request();g=await s.decideFallback(r);Date.now=()=>Date.parse(g.decided_at)-1;try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_EXPIRED')}finally{Date.now=now}checks.push('wall rollback with normal monotonic clock expires immediately');
          const pending=[];for(let i=0;i<16;i++)pending.push(await s.decideFallback(request()));await reject(s.decideFallback(request()),'OFFLINE_FALLBACK_CAPACITY');for(const item of pending)await s.revokeFallback({grant_id:item.id});checks.push('16 pending capacity');
          for(let i=0;i<70;i++)await s.decideFallback(request('deny'));
          const db=await new Promise((ok,no)=>{const q=indexedDB.open('tire-device-history-v1');q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)}),read=(name,key)=>new Promise((ok,no)=>{const q=db.transaction(name).objectStore(name).get(key);q.onsuccess=()=>ok(q.result);q.onerror=()=>no(q.error)});
          const profile=await read('system','profile'),audit=await read('system','fallback-audit');if('receipts' in audit || !audit.encrypted)throw Error('plaintext audit');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:audit.encrypted.iv,additionalData:new TextEncoder().encode(JSON.stringify(['device-fallback-audit@1',profile.profile_id,audit.revision]))},profile.key,audit.encrypted.ciphertext);if(JSON.parse(new TextDecoder().decode(plain)).length!==64)throw Error('ring');checks.push('encrypted audit ring exactly64');
          const write=(name,key,value)=>new Promise((ok,no)=>{const tx=db.transaction(name,'readwrite');tx.oncomplete=()=>ok();tx.onerror=()=>no(tx.error);const store=tx.objectStore(name);if(key===null)store.put(value);else store.put(value,key)});
          r=request();g=await s.decideFallback(r);const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='fallback-audit')throw new DOMException('synthetic quota','QuotaExceededError');return put.call(this,value,key)};try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_QUOTA_EXCEEDED')}finally{IDBObjectStore.prototype.put=put};await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');checks.push('failed encrypted audit commit returns no data and consumes authorization');
          const originalSlot=await read('slots',slot.slot_id);r=request();g=await s.decideFallback(r);const corrupt=structuredClone(originalSlot);new Uint8Array(corrupt.payload.ciphertext)[0]^=1;await write('slots',null,corrupt);await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_CORRUPT');await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');await write('slots',null,originalSlot);checks.push('corrupt payload fails closed and burns grant');
          r=request();g=await s.decideFallback(r);const decrypt=crypto.subtle.decrypt.bind(crypto.subtle);let remove=true;crypto.subtle.decrypt=async function(algorithm,...args){const bytes=await decrypt(algorithm,...args);if(remove&&new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"')){remove=false;await s.remove({slot_id:slot.slot_id,expected_generation:slot.generation})}return bytes};try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_STALE_GENERATION')}finally{crypto.subtle.decrypt=decrypt;await write('slots',null,originalSlot)};checks.push('delete during decrypt is rejected by final slot CAS');
          r=request();g=await s.decideFallback(r);const encrypt=crypto.subtle.encrypt.bind(crypto.subtle);let reset=true;crypto.subtle.encrypt=async function(algorithm,...args){const bytes=await encrypt(algorithm,...args);if(reset&&new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('device-fallback-audit@1')){reset=false;await offlineQA.resetBrowserOfflineOwner()}return bytes};try{await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_OWNER_LOCKED')}finally{crypto.subtle.encrypt=encrypt};await reject(s.consumeFallback({grant_id:g.id,intent:r.intent}),'OFFLINE_FALLBACK_USED');checks.push('owner reset after payload read but before audit commit cannot return late data');const old=(await s.list()).items[0];await s.unlockPreviousOwner({slot_id:old.slot_id,expected_generation:old.generation,allow_previous_owner:true});r=request();r.expected_owner_epoch=(await s.status()).owner_epoch;await reject(s.decideFallback(r),'OFFLINE_OWNER_LOCKED');checks.push('owner reset burns and unlocked prior owner remains excluded');
          return {checks};
        }''',{'slot':slot,'source':source,'model':model,'size':size})
        report['host_checks']=host['checks'];checked('Real IndexedDB host enforces denial/replay/mismatch/TTL/capacity/encrypted audit/owner boundaries')
        assert not report['page_errors'];assert not report['blocked_external'];assert all(row['method']=='GET' or row['path'].endswith('/live-query') for row in report['requests'])
        report['status']='passed';save();context.close();browser.close();browser=None
    except Exception as error:report['status']='failed';report['error_type']=type(error).__name__;report['error']=str(error)[:500];save();raise
    finally:
        if browser:browser.close()
if __name__=='__main__':main()
