"""Isolated actual Chromium IndexedDB/WebCrypto @2 device authorization and policy checks."""
from __future__ import annotations
import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess
from playwright.sync_api import sync_playwright

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = 'https://web-fallback-v2-49.invalid/'
SOURCES = ['apps/web/components/browser-offline-store.ts', 'apps/web/components/browser-device-fallback.ts',
    'apps/web/components/browser-device-sync.ts', 'apps/web/components/local-fallback-values.ts', 'apps/web/components/offline-values.ts', 'apps/web/components/offline-crypto.ts',
    'packages/api-client/src/exact-json.ts', 'packages/api-client/src/device-criteria.ts', 'packages/api-client/src/device-fallback-values.ts',
    'packages/api-client/src/index.ts', 'packages/domain-types/src/query-filter-unicode.json', 'scripts/load_offline_typescript.mjs',
    'scripts/web_device_fallback_v2_qa.py', 'scripts/offline-host-build.mjs']
INITIALIZE = r'''async ({modules,build,descriptor,payload,catalog,directory})=>{
  window.process={env:{NEXT_PUBLIC_TI_OFFLINE_HOST_BUILD:build}};window.__TI_OFFLINE_HOST_BUILD=build;
  window.sdk=await import(modules.sdk);window.qa=await import(modules.store);window.s=qa.browserOfflineStorage;
  const bytes=Uint8Array.from(atob(payload),char=>char.charCodeAt(0));window.pack=sdk.materializeExactMetadata(sdk.parseExactJson(bytes));
  window.originalBytes=bytes;window.originalDescriptor=descriptor;window.syncValues=await import(modules.syncValues);
  sdk.tireApi.offlinePack=async()=>structuredClone(descriptor);sdk.tireApi.offlinePackBytes=async()=>new Response(bytes.slice(),{headers:{'content-type':'application/json','content-length':String(bytes.length),'x-content-sha256':descriptor.sha256}});
  window.catalog=catalog;window.directory=directory;window.ownerScope=descriptor.owner_scope_id;
  const addSource=(id,kind)=>{const source=structuredClone(catalog.items.find(row=>row.effective_status==='ready'));source.source_id=id;source.target_kind=kind;source.management.access_generation=0;catalog.items.push(source);catalog.total++;directory.sources.push({id,name:id,target_kind:kind})};
  addSource('fixture','tire');addSource('synthetic-oem','vehicle');
  sdk.tireApi.fallbackSourceSettings=async()=>({catalog:structuredClone(window.catalog),owner_scope_id:ownerScope,transport_epoch:sdk.apiTransportAuthorityEpoch()});sdk.tireApi.sources=async()=>structuredClone(directory);
  window.slot=await s.install({package_id:descriptor.id,expected_sha256:descriptor.sha256,expected_byte_count:descriptor.byte_count,approved_plan_fingerprint:descriptor.plan_fingerprint,slot_id:crypto.randomUUID(),expected_generation:0,allow_device_storage:true});
  window.openDB=()=>new Promise((resolve,reject)=>{const q=indexedDB.open('tire-device-history-v1',1);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});
  window.dbRead=async(name,key)=>{const db=await openDB();try{return await new Promise((resolve,reject)=>{const q=db.transaction(name).objectStore(name).get(key);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}finally{db.close()}};
  window.originalDecrypt=crypto.subtle.decrypt.bind(crypto.subtle);
  window.audit=async()=>{const owner=await dbRead('system','profile'),record=await dbRead('system','device-fallback-policy-v2');if(!record)return null;
    const body=await originalDecrypt({name:'AES-GCM',iv:record.encrypted.iv,additionalData:new TextEncoder().encode(JSON.stringify(['device-fallback-policy-store@2',owner.profile_id,record.revision]))},owner.key,record.encrypted.ciphertext);return sdk.materializeExactMetadata(sdk.parseExactJson(new Uint8Array(body)))};
  window.replaceAudit=async(data)=>{const owner=await dbRead('system','profile'),record=await dbRead('system','device-fallback-policy-v2'),iv=crypto.getRandomValues(new Uint8Array(12));
    const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(JSON.stringify(['device-fallback-policy-store@2',owner.profile_id,record.revision]))},owner.key,new TextEncoder().encode(sdk.stringifyExactJson(data)));
    const db=await openDB();try{await new Promise((resolve,reject)=>{const tx=db.transaction('system','readwrite');tx.objectStore('system').put({revision:record.revision,encrypted:{iv,ciphertext}},'device-fallback-policy-v2');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}finally{db.close()}return record.revision};
  window.startReads=()=>{window.payloadReads=0;window.firstBodyAudit=null;crypto.subtle.decrypt=async function(algorithm,...args){if(new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"')){payloadReads++;if(firstBodyAudit===null)firstBodyAudit=(await audit())?.receipts.at(-1)?.state||'missing'}return originalDecrypt(algorithm,...args)}};
  window.qaId=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
  window.code=async promise=>{try{await promise;return 'unexpected_success'}catch(error){return error.code||error.name}};
  window.newRequest=async(kind='tire',options={})=>{const status=await s.fallbackStatus(),member=pack.members.find(member=>member.reference.kind===({tire:'tire',vehicle_fitments:'vehicle',recall_campaign:'recall',recall_search:'recall_search'}[kind])),query=kind==='tire'?{size:member.payload.variant.size}:kind==='vehicle_fitments'?{vehicle_id:member.payload.vehicle.id}:kind==='recall_campaign'?{campaign_number:member.payload.evidence.campaign_number}:member.payload.query;
    const intent=await sdk.createDeviceFallbackIntent(kind,options.query||query,options.filters||[],member.source.source_id,0,options.failure||{scope:'api_transport',reason:'api_network_unavailable',query_id:null},crypto.randomUUID(),{runtime_session_id:status.authority.runtime_session_id,authority_revision:status.authority.authority_revision},options.policy||'ask');return {intent,slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:status.profile_id,expected_owner_epoch:status.owner_epoch,decision:'allow'}};
  window.policy=async(mode='source_allow',options={})=>{const status=await s.fallbackStatus(),kind=options.kind||'tire',source=options.source||'fixture';
    const scope=options.scope||{kind:'source',source_id:source,access_generation:0,query_kinds:[kind]},allow=mode.endsWith('_allow');
    const request={mode,scope,binding:allow?status.package_bindings[0]:null,allow_same_scope_sync_binding_advance:allow&&options.advance===true,expected_profile_id:status.profile_id,expected_owner_epoch:status.owner_epoch,authority:{runtime_session_id:status.authority.runtime_session_id,authority_revision:status.authority.authority_revision},policy_id:options.previous?.policy_id||null,expected_policy_revision:options.previous?.policy_revision||0,expires_in_seconds:options.ttl||900};
    const preview=await s.previewFallbackPolicy(request);return s.applyFallbackPolicy({preview_id:preview.preview_id,expected_fingerprint:preview.fingerprint,expected_policy_revision:request.expected_policy_revision,allow_continuous_history_fallback:true})};
  return {secure:isSecureContext,key_extractable:(await dbRead('system','profile')).key.extractable,slot_sha:slot.sha256};
}'''
CASES = {
 'formal_uuid_case_shared_identity_preserves_v1_v2_and_blocks_old_and_new':r'''async()=>{
   await s.refreshFallbackAuthority();const legacy=await import(legacyModule),host=await s.status(),rows=[];
   for(const [qid,denyUpper] of [['abcdef12-abcd-4abc-8abc-abcdef123456',true],['abcdef13-abcd-4abc-8abc-abcdef123456',false]]){
     const requests=[],old=[];for(const query_id of [qid,qid.toUpperCase()]){const failure={scope:'source_response',reason:'upstream_timeout',query_id},v2=await newRequest('tire',{failure}),v1={...v2,intent:await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,failure,crypto.randomUUID())};requests.push({v1,v2});old.push({v1:await s.decideFallback(v1),v2:await s.decideFallbackV2(v2)})}
     const raw=old.every((grants,i)=>grants.v1.intent.failure.query_id===requests[i].v1.intent.failure.query_id&&grants.v2.intent.failure.query_id===requests[i].v2.intent.failure.query_id),fingerprints=requests[0].v1.intent.query_fingerprint===requests[1].v1.intent.query_fingerprint&&requests[0].v2.intent.query_fingerprint===requests[1].v2.intent.query_fingerprint;
     await sdk.tireApi.consent(denyUpper?qid.toUpperCase():qid,'deny');startReads();const blocked=[];
     for(let i=0;i<requests.length;i++){const {v1,v2}=requests[i];blocked.push(await code(s.consumeFallback({grant_id:old[i].v1.id,intent:v1.intent})),await code(s.consumeFallbackV2({grant_id:old[i].v2.id,intent:v2.intent})));const fresh=await newRequest('tire',{failure:v2.intent.failure}),auth=await s.authorizeFallback(Object.fromEntries(Object.entries(fresh).filter(([key])=>key!=='decision')));blocked.push(auth.state,await code(s.decideFallbackV2(await newRequest('tire',{failure:v2.intent.failure}))),await code(s.decideFallback({...v1,intent:await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,v1.intent.failure,crypto.randomUUID())})))}
     rows.push({raw,fingerprints,blocked,reads:payloadReads});
   }
   const ledger=(await audit()).warehouse_denials,other=await s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:'abcdef14-abcd-4abc-8abc-abcdef123456'}}));
   return {pass:rows.every(row=>row.raw&&row.fingerprints&&row.reads===0&&row.blocked.every(value=>value==='blocked'||value==='OFFLINE_FALLBACK_NEVER'))&&ledger.query_ids.length===2&&ledger.query_ids.every(key=>key===key.toLowerCase())&&other.state==='allowed',rows,ledger_keys:ledger.query_ids,other:other.state};
 }''',
 'formal_uuid_case_late_owned_deny_discards_v2_consumed_result':r'''async()=>{
   await s.refreshFallbackAuthority();const qid='abcdef15-abcd-4abc-8abc-abcdef123456',request=await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_network_error',query_id:qid.toUpperCase()}}),grant=await s.decideFallbackV2(request);startReads();const observed=crypto.subtle.decrypt.bind(crypto.subtle);let denied=false;
   crypto.subtle.decrypt=async function(algorithm,...args){const bytes=await observed(algorithm,...args);if(!denied&&payloadReads===2&&new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"')){denied=true;await sdk.tireApi.consent(qid,'deny')}return bytes};
   const error=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent})),receipt=(await audit()).receipts.at(-1);return {pass:denied&&error==='OFFLINE_FALLBACK_NEVER'&&receipt.state==='consumed'&&receipt.intent.failure.query_id===qid.toUpperCase(),denied,error,receipt:receipt.state,raw:receipt.intent.failure.query_id,reads:payloadReads};
 }''',
 'formal_uuid_old_encrypted_mixed_case_ledger_cas_dedup':r'''async()=>{
   await s.refreshFallbackAuthority();await policy('ask');const status=await s.fallbackStatus(),qid='abcdef16-abcd-4abc-8abc-abcdef123456',data=await audit();data.warehouse_denials={runtime_session_id:status.authority.runtime_session_id,owner_epoch:status.owner_epoch,transport_epoch:sdk.apiTransportAuthorityEpoch(),owner_scope_id:status.authority.owner_scope_id,query_ids:[qid.toUpperCase(),qid,'AbCdEf16-aBcD-4aBc-8aBc-aBcDeF123456','OpaqueQueryA','opaquequerya'],overflow:false};const before=await replaceAudit(data);startReads();await s.fallbackStatus();const first=(await dbRead('system','device-fallback-policy-v2')).revision,ledger=(await audit()).warehouse_denials;await s.fallbackStatus();const second=(await dbRead('system','device-fallback-policy-v2')).revision;
   const blocks=[];for(const query_id of [qid,qid.toUpperCase()])blocks.push(await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id}}))));
   return {pass:first===before+1&&second===first&&JSON.stringify(ledger.query_ids)===JSON.stringify([qid,'OpaqueQueryA','opaquequerya'])&&blocks.every(value=>value==='OFFLINE_FALLBACK_NEVER')&&payloadReads===0,before,first,second,keys:ledger.query_ids,blocks,reads:payloadReads};
 }''',
 'formal_uuid_ledger_migration_preserves_unrelated_pending_and_preview':r'''async()=>{
   await s.refreshFallbackAuthority();await policy('ask');const status=await s.fallbackStatus(),qid='abcdef21-abcd-4abc-8abc-abcdef123456',other='abcdef22-abcd-4abc-8abc-abcdef123456',request=await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:other.toUpperCase()}}),v2=await s.decideFallbackV2(request),legacy=await import(legacyModule),intent=await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,{scope:'api_transport',reason:'api_network_unavailable',query_id:null},crypto.randomUUID()),v1=await s.decideFallback({...request,intent});
   const preview=await s.previewFallbackPolicy({mode:'ask',scope:{kind:'source',source_id:'fixture',access_generation:0,query_kinds:['tire']},binding:null,allow_same_scope_sync_binding_advance:false,expected_profile_id:status.profile_id,expected_owner_epoch:status.owner_epoch,authority:{runtime_session_id:status.authority.runtime_session_id,authority_revision:status.authority.authority_revision},policy_id:null,expected_policy_revision:0,expires_in_seconds:900}),data=await audit();data.warehouse_denials={runtime_session_id:status.authority.runtime_session_id,owner_epoch:status.owner_epoch,transport_epoch:sdk.apiTransportAuthorityEpoch(),owner_scope_id:status.authority.owner_scope_id,query_ids:[qid.toUpperCase(),qid],overflow:false};const before=await replaceAudit(data);startReads();await s.fallbackStatus();const after=(await dbRead('system','device-fallback-policy-v2')).revision,metadataReads=payloadReads,old=await code(s.consumeFallback({grant_id:v1.id,intent})),local=await s.consumeFallbackV2({grant_id:v2.id,intent:request.intent}).then(value=>value.data_state,error=>error.code),applied=await s.applyFallbackPolicy({preview_id:preview.preview_id,expected_fingerprint:preview.fingerprint,expected_policy_revision:0,allow_continuous_history_fallback:true}).then(value=>value.state,error=>error.code);
   return {pass:after===before+1&&metadataReads===0&&old==='OFFLINE_FALLBACK_UNSUPPORTED'&&local==='local_snapshot'&&applied==='enabled'&&firstBodyAudit==='consumed',before,after,metadataReads,old,local,applied,first:firstBodyAudit,reads:payloadReads};
 }''',
 'formal_uuid_aliases_do_not_spend_capacity_or_clear_overflow':r'''async()=>{
   await s.refreshFallbackAuthority();await policy('ask');const status=await s.fallbackStatus(),qid='abcdef17-abcd-4abc-8abc-abcdef123456',data=await audit();data.warehouse_denials={runtime_session_id:status.authority.runtime_session_id,owner_epoch:status.owner_epoch,transport_epoch:sdk.apiTransportAuthorityEpoch(),owner_scope_id:status.authority.owner_scope_id,query_ids:[qid.toUpperCase(),qid,...Array.from({length:1022},(_,i)=>qaId(810000+i))],overflow:false};await replaceAudit(data);await s.fallbackStatus();const migrated=(await audit()).warehouse_denials.query_ids.length;await sdk.tireApi.consent(qid.toUpperCase(),'deny');const alias=(await audit()).warehouse_denials;await sdk.tireApi.consent(qaId(819998),'deny');const full=(await audit()).warehouse_denials;await sdk.tireApi.consent(qaId(819999),'deny');const overflow=(await audit()).warehouse_denials;startReads();const blocked=await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:qid.toUpperCase()}})));await sdk.tireApi.consent(qid,'deny');const preserved=(await audit()).warehouse_denials;
   return {pass:migrated===1023&&alias.query_ids.length===1023&&!alias.overflow&&full.query_ids.length===1024&&!full.overflow&&overflow.query_ids.length===1024&&overflow.overflow&&overflow.query_ids[0]===qid&&preserved.overflow&&blocked==='OFFLINE_FALLBACK_CAPACITY'&&payloadReads===0,migrated,alias_count:alias.query_ids.length,full_count:full.query_ids.length,overflow:overflow.overflow,preserved_overflow:preserved.overflow,blocked,reads:payloadReads};
 }''',
 'formal_uuid_migration_write_failure_keeps_old_encrypted_state_then_retries':r'''async()=>{
   await s.refreshFallbackAuthority();await policy('ask');const status=await s.fallbackStatus(),qid='abcdef18-abcd-4abc-8abc-abcdef123456',data=await audit();data.warehouse_denials={runtime_session_id:status.authority.runtime_session_id,owner_epoch:status.owner_epoch,transport_epoch:sdk.apiTransportAuthorityEpoch(),owner_scope_id:status.authority.owner_scope_id,query_ids:[qid.toUpperCase(),qid],overflow:false};const before=await replaceAudit(data),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='device-fallback-policy-v2')throw new DOMException('private migration injection','QuotaExceededError');return put.call(this,value,key)};startReads();let failed;try{failed=await code(s.fallbackStatus())}finally{IDBObjectStore.prototype.put=put}const retained=(await audit()).warehouse_denials.query_ids,retainedRevision=(await dbRead('system','device-fallback-policy-v2')).revision;await s.fallbackStatus();const after=(await dbRead('system','device-fallback-policy-v2')).revision,blocked=await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:qid.toUpperCase()}})));
   return {pass:failed==='OFFLINE_QUOTA_EXCEEDED'&&retainedRevision===before&&retained.length===2&&retained[0]===qid.toUpperCase()&&after===before+1&&blocked==='OFFLINE_FALLBACK_NEVER'&&payloadReads===0,failed,before,retainedRevision,after,retained,blocked,reads:payloadReads};
 }''',
 'formal_uuid_migration_does_not_mask_old_malformed_duplicates':r'''async()=>{
   await s.refreshFallbackAuthority();await policy('ask');const status=await s.fallbackStatus(),qid='abcdef19-abcd-4abc-8abc-abcdef123456',data=await audit();data.warehouse_denials={runtime_session_id:status.authority.runtime_session_id,owner_epoch:status.owner_epoch,transport_epoch:sdk.apiTransportAuthorityEpoch(),owner_scope_id:status.authority.owner_scope_id,query_ids:[qid.toUpperCase(),qid.toUpperCase()],overflow:false};const before=await replaceAudit(data);startReads();const error=await code(s.fallbackStatus()),after=(await dbRead('system','device-fallback-policy-v2')).revision;
   return {pass:error==='OFFLINE_CORRUPT'&&before===after&&payloadReads===0,error,before,after,reads:payloadReads};
 }''',
 'formal_uuid_reload_does_not_resurrect_grants_or_inherit_old_runtime_denial':r'''async()=>{
   await s.refreshFallbackAuthority();const qid='abcdef20-abcd-4abc-8abc-abcdef123456',failure={scope:'source_response',reason:'upstream_timeout',query_id:qid.toUpperCase()},request=await newRequest('tire',{failure}),legacy=await import(legacyModule),intent=await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,failure,crypto.randomUUID()),v1=await s.decideFallback({...request,intent}),v2=await s.decideFallbackV2(request);await sdk.tireApi.consent(qid,'deny');return {pass:true,reload_denial:{qid,v1,v2,old_runtime:request.intent.authority.runtime_session_id}};
 }''',
 'failed_owner_reset_keeps_denial_fault_closed_until_successful_owner_transaction':r'''async()=>{
   await s.refreshFallbackAuthority();const before=await s.fallbackStatus(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='device-fallback-policy-v2')throw new DOMException('private injection','QuotaExceededError');return put.call(this,value,key)};
   let resetError;try{await sdk.tireApi.consent(crypto.randomUUID(),'deny');resetError=await code(qa.resetBrowserOfflineOwner())}finally{IDBObjectStore.prototype.put=put};await s.refreshFallbackAuthority();startReads();const blocked=await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:crypto.randomUUID()}}))),after=await s.fallbackStatus();await qa.resetBrowserOfflineOwner();await s.refreshFallbackAuthority();const status=await s.fallbackStatus(),member=pack.members.find(row=>row.reference.kind==='tire'),intent=await sdk.createDeviceFallbackIntent('tire',{size:member.payload.variant.size},[],'fixture',0,{scope:'source_response',reason:'upstream_timeout',query_id:crypto.randomUUID()},crypto.randomUUID(),{runtime_session_id:status.authority.runtime_session_id,authority_revision:status.authority.authority_revision}),newSlot=await s.install({package_id:originalDescriptor.id,expected_sha256:originalDescriptor.sha256,expected_byte_count:originalDescriptor.byte_count,approved_plan_fingerprint:originalDescriptor.plan_fingerprint,slot_id:crypto.randomUUID(),expected_generation:0,allow_device_storage:true}),grant=await s.decideFallbackV2({intent,slot_id:newSlot.slot_id,expected_generation:newSlot.generation,expected_sha256:newSlot.sha256,expected_profile_id:status.profile_id,expected_owner_epoch:status.owner_epoch,decision:'allow'});
   return {pass:resetError==='OFFLINE_QUOTA_EXCEEDED'&&after.owner_epoch===before.owner_epoch&&blocked==='OFFLINE_FALLBACK_CAPACITY'&&status.owner_epoch===before.owner_epoch+1&&grant.state==='allowed'&&payloadReads===0,resetError,blocked,epochs:[before.owner_epoch,after.owner_epoch,status.owner_epoch],reads:payloadReads};
 }''',
 'same_scope_sync_atomically_advances_full_whitelist_and_invalidates_old_grant':r'''async()=>{
   await s.refreshFallbackAuthority();const scope={kind:'session',sources:[{source_id:'fixture',access_generation:0,query_kinds:['tire']},{source_id:'synthetic-oem',access_generation:0,query_kinds:['vehicle_fitments']},{source_id:'nhtsa-us-recalls',access_generation:0,query_kinds:['recall_campaign','recall_search']}]},approved=await policy('session_allow',{scope,advance:true}),oldRequest=await newRequest(),oldGrant=await s.decideFallbackV2(oldRequest),host=await s.status();
   const preview=await s.previewSyncPolicy({slot_id:slot.slot_id,expected_generation:slot.generation,expected_profile_id:host.profile_id,expected_owner_epoch:host.owner_epoch,interval_seconds:900,conditions:{network:'any',power:'any'}}),sync=await s.applySyncPolicy({preview_id:preview.preview_id,expected_fingerprint:preview.fingerprint,expected_policy_revision:preview.expected_policy_revision,allow_continuous_history_updates:true});
   const candidate=sdk.cloneExactDeviceValue(pack);candidate.package_id=crypto.randomUUID();candidate.base_pack_id=slot.package_id;candidate.plan_fingerprint='f'.repeat(64);candidate.created_at=new Date().toISOString();candidate.members.find(member=>member.reference.kind==='tire').payload.variant.facts.qa_history_update='separate synthetic approved fixture';
   const bytes=new TextEncoder().encode(sdk.stringifyExactJson(candidate)),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),value=>value.toString(16).padStart(2,'0')).join(''),descriptor={...originalDescriptor,id:candidate.package_id,plan_id:crypto.randomUUID(),base_pack_id:slot.package_id,plan_fingerprint:candidate.plan_fingerprint,sha256:hash,byte_count:bytes.length,created_at:candidate.created_at,content_created_at:candidate.created_at,download_path:'/v1/offline-packs/'+candidate.package_id+'/download?mode=history'},plan={schema:'offline-pack-plan@2',id:descriptor.plan_id,package_id:descriptor.id,fingerprint:descriptor.plan_fingerprint,content_sha256:hash,owner_scope_id:ownerScope,base_pack_id:slot.package_id,requested_scope:sync.scope,capacity:sync.capacity,state:'ready',can_confirm:true,measured_bytes:bytes.length,expires_at:new Date(Date.now()+600000).toISOString(),resolved:candidate.members,contexts:candidate.contexts,documents:candidate.documents,omissions:[],counts:descriptor.counts};
   sdk.tireApi.offlineSyncPrepareV2=async()=>({schema:'offline-pack-update@2',state:'planned',mode:'history',base_pack_id:slot.package_id,base_semantic_digest:await syncValues.deviceSyncSemanticDigestFromBytes(originalBytes),current_semantic_digest:await syncValues.deviceSyncSemanticDigestFromBytes(bytes),base_pack:originalDescriptor,plan,source_refresh_performed:false});sdk.tireApi.offlineSyncConfirm=async()=>descriptor;sdk.tireApi.offlineSyncPack=async()=>descriptor;sdk.tireApi.offlineSyncBytes=async()=>new Response(bytes,{headers:{'content-type':'application/json','content-length':String(bytes.length),'x-content-sha256':hash}});
   const run=await s.runSyncPolicy({policy_id:sync.policy_id,expected_policy_revision:sync.policy_revision,trigger:'manual'});const status=await s.fallbackStatus(),saved=status.policies.find(row=>row.policy_id===approved.policy_id),newSlot=(await s.list()).items.find(row=>row.slot_id===slot.slot_id);startReads();const old=await code(s.consumeFallbackV2({grant_id:oldGrant.id,intent:oldRequest.intent}));slot=newSlot;const fresh=await newRequest(),auto=await s.authorizeFallback(Object.fromEntries(Object.entries(fresh).filter(([key])=>key!=='decision')));
   return {pass:run.state==='succeeded'&&saved.state==='enabled'&&saved.policy_revision===approved.policy_revision+1&&saved.binding.generation===2&&saved.binding.sha256===hash&&saved.binding.history_scope_fingerprint===approved.binding.history_scope_fingerprint&&old==='OFFLINE_FALLBACK_USED'&&auto.state==='allowed'&&auto.grant.fallback_authorization.policy_revision===saved.policy_revision&&payloadReads===0,run:run.state,run_reason:run.reason,policy:saved.state,generation:saved.binding.generation,old,auto:auto.state,reads:payloadReads};
 }''',
 'warehouse_actual_sdk_deny_blocks_same_query_new_attempt_and_legacy':r'''async()=>{
   await s.refreshFallbackAuthority();const qid=crypto.randomUUID(),failure={scope:'source_response',reason:'upstream_timeout',query_id:qid},request=await newRequest('tire',{failure}),grant=await s.decideFallbackV2(request);await sdk.tireApi.consent(qid,'deny');startReads();
   const consumed=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent})),retry=await newRequest('tire',{failure}),authorized=await s.authorizeFallback(Object.fromEntries(Object.entries(retry).filter(([key])=>key!=='decision'))),decided=await code(s.decideFallbackV2(await newRequest('tire',{failure}))),host=await s.status(),legacy=await import(legacyModule),intent=await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,failure,crypto.randomUUID()),old=await code(s.decideFallback({...request,intent}));
   const ledger=(await audit()).warehouse_denials,other=await newRequest('tire',{failure:{...failure,query_id:crypto.randomUUID()}}),fresh=await s.decideFallbackV2(other);
   return {pass:consumed==='OFFLINE_FALLBACK_NEVER'&&authorized.state==='blocked'&&decided==='OFFLINE_FALLBACK_NEVER'&&old==='OFFLINE_FALLBACK_NEVER'&&ledger.query_ids.includes(qid)&&fresh.state==='allowed'&&payloadReads===0,consumed,authorized:authorized.state,decided,old,ledger_count:ledger.query_ids.length,reads:payloadReads};
 }''',
 'warehouse_deny_during_business_body_discards_consumed_result':r'''async()=>{
   await s.refreshFallbackAuthority();const qid=crypto.randomUUID(),request=await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_network_error',query_id:qid}}),grant=await s.decideFallbackV2(request);startReads();const observed=crypto.subtle.decrypt.bind(crypto.subtle);let denied=false;
   crypto.subtle.decrypt=async function(algorithm,...args){const bytes=await observed(algorithm,...args);if(!denied&&payloadReads===2&&new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"')){denied=true;await sdk.tireApi.consent(qid,'deny')}return bytes};
   const error=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent}));return {pass:denied&&error==='OFFLINE_FALLBACK_NEVER'&&(await audit()).receipts.at(-1).state==='consumed',denied,error,reads:payloadReads};
 }''',
 'warehouse_denial_requires_success201_and_matching_response_decision':r'''async()=>{
   await s.refreshFallbackAuthority();for(const qid of [qaId(200),qaId(201),qaId(202),qaId(204)])await sdk.tireApi.consent(qid,'deny');await sdk.tireApi.consent(qaId(203),'allow');startReads();const grants=[];
   for(const qid of [qaId(200),qaId(201),qaId(202),qaId(203),qaId(204)])grants.push(await s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:qid}})));
   return {pass:grants.every(grant=>grant.state==='allowed')&&!(await audit()).warehouse_denials&&payloadReads===0,grants:grants.length,reads:payloadReads};
 }''',
 'warehouse_denial_write_failure_closes_source_fallback_zero_body':r'''async()=>{
   await s.refreshFallbackAuthority();const qid=crypto.randomUUID(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='device-fallback-policy-v2')throw new DOMException('private injection','QuotaExceededError');return put.call(this,value,key)};
   try{await sdk.tireApi.consent(qid,'deny')}finally{IDBObjectStore.prototype.put=put};startReads();const source=await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:crypto.randomUUID()}}))),api=await s.decideFallbackV2(await newRequest());return {pass:source==='OFFLINE_FALLBACK_CAPACITY'&&api.state==='allowed'&&payloadReads===0,source,reads:payloadReads};
 }''',
 'warehouse_denials_1024_no_eviction_overflow_closed':r'''async()=>{
   await s.refreshFallbackAuthority();for(let i=0;i<1025;i++)await sdk.tireApi.consent(qaId(700000+i),'deny');startReads();const ledger=(await audit()).warehouse_denials,blocked=await code(s.decideFallbackV2(await newRequest('tire',{failure:{scope:'source_response',reason:'upstream_timeout',query_id:qaId(799999)}})));
   return {pass:ledger.query_ids.length===1024&&ledger.query_ids.includes(qaId(700000))&&!ledger.query_ids.includes(qaId(701024))&&ledger.overflow&&blocked==='OFFLINE_FALLBACK_CAPACITY'&&payloadReads===0,count:ledger.query_ids.length,overflow:ledger.overflow,blocked,reads:payloadReads};
 }''',
 'policy_capacity_revoke_reapprove_and_stale_CAS':r'''async()=>{
   await s.refreshFallbackAuthority();startReads();const policies=[];for(let i=0;i<16;i++)policies.push(await policy('ask'));const full=await code(policy('ask')),paused=await s.pauseFallbackPolicy({policy_id:policies[0].policy_id,expected_policy_revision:policies[0].policy_revision}),stillFull=await code(policy('ask')),same=await policy('ask',{previous:paused}),revoked=await s.revokeFallbackPolicy({policy_id:same.policy_id,expected_policy_revision:same.policy_revision}),newPolicy=await policy('ask'),fullReapprove=await code(policy('ask',{previous:revoked}));await s.revokeFallbackPolicy({policy_id:newPolicy.policy_id,expected_policy_revision:newPolicy.policy_revision});const reapproved=await policy('ask',{previous:revoked}),stale=await code(policy('ask',{previous:revoked}));
   return {pass:full==='OFFLINE_FALLBACK_CAPACITY'&&stillFull===full&&same.policy_id===paused.policy_id&&fullReapprove===full&&reapproved.policy_id===revoked.policy_id&&reapproved.policy_revision===revoked.policy_revision+1&&stale==='OFFLINE_FALLBACK_POLICY_CHANGED'&&payloadReads===0,full,stillFull,fullReapprove,stale,reads:payloadReads};
 }''',
 'policy_latest64_prunes_only_oldest_revoked_and_missing_id_fails':r'''async()=>{
   await s.refreshFallbackAuthority();startReads();const live=await policy('ask'),paused=await s.pauseFallbackPolicy({policy_id:live.policy_id,expected_policy_revision:live.policy_revision}),archived=[];
   for(let i=0;i<65;i++){const approved=await policy('ask');archived.push(await s.revokeFallbackPolicy({policy_id:approved.policy_id,expected_policy_revision:approved.policy_revision}))}
   const records=(await audit()).policies,pruned=archived.filter(old=>!records.some(row=>row.policy_id===old.policy_id)),expected=[...archived].sort((a,b)=>Date.parse(a.updated_at)-Date.parse(b.updated_at)||(a.policy_id<b.policy_id?-1:1)).slice(0,2),missing=await code(policy('ask',{previous:pruned[0]}));
   return {pass:records.length===64&&records.some(row=>row.policy_id===paused.policy_id&&row.state==='paused')&&pruned.map(row=>row.policy_id).sort().join()===expected.map(row=>row.policy_id).sort().join()&&missing==='OFFLINE_FALLBACK_POLICY_CHANGED'&&payloadReads===0,count:records.length,pruned:pruned.length,missing,reads:payloadReads};
 }''',
 'owner_reset_atomically_revokes_archive_and_old_epoch_cannot_reapprove':r'''async()=>{
   await s.refreshFallbackAuthority();const a=await policy('ask'),b=await policy('never'),paused=await s.pauseFallbackPolicy({policy_id:b.policy_id,expected_policy_revision:b.policy_revision}),before=await s.fallbackStatus();startReads();await qa.resetBrowserOfflineOwner();const after=await s.fallbackStatus(),records=(await audit()).policies;await s.refreshFallbackAuthority();const reuse=await code(policy('ask',{previous:records.find(row=>row.policy_id===a.policy_id)})),fresh=await policy('ask');
   return {pass:after.owner_epoch===before.owner_epoch+1&&after.authority.state==='unknown'&&after.policies.length===0&&records.every(row=>row.state==='revoked'&&row.reason==='OFFLINE_FALLBACK_OWNER_CHANGED')&&records.find(row=>row.policy_id===a.policy_id).policy_revision===a.policy_revision+1&&records.find(row=>row.policy_id===b.policy_id).policy_revision===paused.policy_revision+1&&reuse==='OFFLINE_OWNER_LOCKED'&&fresh.state==='enabled'&&payloadReads===0,epoch:after.owner_epoch,archive:records.map(row=>({state:row.state,reason:row.reason,revision:row.policy_revision})),reuse,reads:payloadReads};
 }''',
 'owner_reset_failed_sidecar_write_keeps_epoch_and_policy_atomic':r'''async()=>{
   await s.refreshFallbackAuthority();const approved=await policy('ask'),before=await s.fallbackStatus(),put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='device-fallback-policy-v2')throw new DOMException('private injection','QuotaExceededError');return put.call(this,value,key)};let error;try{error=await code(qa.resetBrowserOfflineOwner())}finally{IDBObjectStore.prototype.put=put};const after=await s.fallbackStatus(),saved=(await audit()).policies.find(row=>row.policy_id===approved.policy_id);
   return {pass:error==='OFFLINE_QUOTA_EXCEEDED'&&after.owner_epoch===before.owner_epoch&&saved.state==='enabled'&&saved.policy_revision===approved.policy_revision,error,epoch:after.owner_epoch,state:saved.state};
 }''',
 'session_ask_and_never_are_runtime_only_after_reload':r'''async()=>{
   await s.refreshFallbackAuthority();const scope={kind:'session',sources:[{source_id:'fixture',access_generation:0,query_kinds:['tire']}]},ask=await policy('ask',{scope}),never=await policy('never',{scope});return {pass:true,reload_session_policies:[ask.policy_id,never.policy_id]};
 }''',
 'cold_authority_unknown_and_real_catalog_13':r'''async()=>{startReads();const status=await s.fallbackStatus(),request=await newRequest();const blocked=await code(s.decideFallbackV2(request));const auth=await s.refreshFallbackAuthority();return {pass:status.authority.state==='unknown'&&status.authority.authority_revision===0&&blocked==='OFFLINE_FALLBACK_AUTHORITY_UNKNOWN'&&auth.state==='last_observed'&&auth.sources.length===13&&auth.sources.some(row=>row.source_id==='xiaomi-cn-vehicles'&&row.query_kinds.includes('vehicle_fitments'))&&payloadReads===0,blocked,source_count:auth.sources.length,payload_reads:payloadReads}}''',
 'four_domain_original_history_and_durable_consumed':r'''async()=>{await s.refreshFallbackAuthority();const results=[];for(const kind of ['tire','vehicle_fitments','recall_campaign','recall_search']){const request=await newRequest(kind);startReads();const grant=await s.decideFallbackV2(request);const response=await s.consumeFallbackV2({grant_id:grant.id,intent:request.intent});const receipts=(await audit()).receipts.filter(row=>row.id===grant.id);results.push({kind,first:firstBodyAudit,reads:payloadReads,states:receipts.map(row=>row.state),members:response.members.length,citations:response.citations.length,local:response.complete_query_result===false,token:kind==='tire'?response.members[0]?.payload.variant.facts.reference_int.token:null});}return {pass:results.every(row=>row.first==='consumed'&&row.members>0&&row.citations>0&&row.states.join(',')==='allowed,consumed'&&row.local)&&results[0].token==='9007199254740993',results}}''',
 'ask_metadata_preserves_attempt_then_once':r'''async()=>{await s.refreshFallbackAuthority();const request=await newRequest();startReads();const authorization=await s.authorizeFallback(Object.fromEntries(Object.entries(request).filter(([key])=>key!=='decision'))),before=payloadReads;const grant=await s.decideFallbackV2(request);return {pass:authorization.state==='ask'&&before===0&&grant.state==='allowed',state:authorization.state,reads_before_once:before}}''',
 'policy_preview_apply_and_auto_are_separate_and_metadata_only':r'''async()=>{await s.refreshFallbackAuthority();startReads();const approved=await policy();const request=await newRequest();const result=await s.authorizeFallback(Object.fromEntries(Object.entries(request).filter(([key])=>key!=='decision'))),metadataReads=payloadReads;const value=await s.consumeFallbackV2({grant_id:result.grant.id,intent:request.intent});return {pass:approved.mode==='source_allow'&&result.state==='allowed'&&result.grant.fallback_authorization.type==='policy_once'&&metadataReads===0&&firstBodyAudit==='consumed'&&value.fallback_authorization.policy_id===approved.policy_id,metadata_reads:metadataReads,first:firstBodyAudit,authorization:value.fallback_authorization}}''',
 'never_blocks_new_v2_old_v1_and_old_grant_without_generation_bypass':r'''async()=>{await s.refreshFallbackAuthority();const request=await newRequest();const grant=await s.decideFallbackV2(request);await policy('never');startReads();const old=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent}));const second=await newRequest();const blocked=await s.authorizeFallback(Object.fromEntries(Object.entries(second).filter(([key])=>key!=='decision')));const fresh=await code(s.decideFallbackV2(second));const legacy=(await import(window.legacyModule)).createFallbackIntent;const v1=await legacy({model:'Fixture Tire',size:'265/40ZR20'},[],'fixture',999,{scope:'api_transport',reason:'api_network_unavailable',query_id:null},crypto.randomUUID());const downgraded=await code(s.decideFallback({...second,intent:v1}));return {pass:old!=='unexpected_success'&&blocked.state==='blocked'&&fresh==='OFFLINE_FALLBACK_NEVER'&&downgraded==='OFFLINE_FALLBACK_NEVER'&&payloadReads===0,old,blocked:blocked.state,fresh,downgraded,reads:payloadReads}}''',
 'request_never_burns_attempt_even_when_policy_allows':r'''async()=>{await s.refreshFallbackAuthority();await policy();const request=await newRequest('tire',{policy:'never'});startReads();const blocked=await s.authorizeFallback(Object.fromEntries(Object.entries(request).filter(([key])=>key!=='decision')));request.intent.fallback_policy='ask';const retry=await code(s.decideFallbackV2(request));return {pass:blocked.state==='blocked'&&retry==='OFFLINE_FALLBACK_USED'&&payloadReads===0,blocked:blocked.state,retry,reads:payloadReads}}''',
 'audit_write_failure_is_zero_body_and_burned':r'''async()=>{await s.refreshFallbackAuthority();const request=await newRequest(),grant=await s.decideFallbackV2(request);startReads();const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,key){if(this.name==='system'&&key==='device-fallback-policy-v2')throw new DOMException('private injection','QuotaExceededError');return put.call(this,value,key)};let error;try{error=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent}))}finally{IDBObjectStore.prototype.put=put};return {pass:error==='OFFLINE_QUOTA_EXCEEDED'&&payloadReads===0&&(await code(s.decideFallbackV2(request)))==='OFFLINE_FALLBACK_USED',error,reads:payloadReads}}''',
 'bad_body_remains_consumed_and_replay_burned':r'''async()=>{await s.refreshFallbackAuthority();const request=await newRequest(),grant=await s.decideFallbackV2(request),db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('slots','readwrite'),store=tx.objectStore('slots'),q=store.get(slot.slot_id);q.onsuccess=()=>{const row=q.result,b=new Uint8Array(row.payload.ciphertext);b[0]^=1;row.payload.ciphertext=b.buffer;store.put(row)};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();startReads();const error=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent}));return {pass:error!=='unexpected_success'&&(await audit()).receipts.at(-1).state==='consumed'&&firstBodyAudit==='consumed'&&(await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent})))==='OFFLINE_FALLBACK_USED',error,reads:payloadReads,first:firstBodyAudit}}''',
 'never_applied_during_business_body_discards_late_result':r'''async()=>{await s.refreshFallbackAuthority();const request=await newRequest(),grant=await s.decideFallbackV2(request);startReads();const observed=crypto.subtle.decrypt.bind(crypto.subtle);let changed=false;crypto.subtle.decrypt=async function(algorithm,...args){const bytes=await observed(algorithm,...args);if(!changed&&payloadReads===2&&new TextDecoder().decode(algorithm.additionalData||new Uint8Array()).includes('"payload"')){changed=true;await policy('never')}return bytes};const error=await code(s.consumeFallbackV2({grant_id:grant.id,intent:request.intent}));return {pass:changed&&error==='OFFLINE_FALLBACK_NEVER'&&(await audit()).receipts.at(-1).state==='consumed',changed,error,reads:payloadReads}}''',
 'permission_generation_refresh_invalidates_policy_pending':r'''async()=>{await s.refreshFallbackAuthority();const approved=await policy(),request=await newRequest(),allowed=await s.authorizeFallback(Object.fromEntries(Object.entries(request).filter(([key])=>key!=='decision')));catalog.items.find(row=>row.source_id==='fixture').management.access_generation=1;const auth=await s.refreshFallbackAuthority();startReads();const stale=await code(s.consumeFallbackV2({grant_id:allowed.grant.id,intent:request.intent}));const saved=(await s.fallbackStatus()).policies.find(row=>row.policy_id===approved.policy_id);return {pass:saved.state==='paused'&&saved.reason==='source_authority_changed'&&stale==='OFFLINE_FALLBACK_USED'&&payloadReads===0,policy:saved.state,reason:saved.reason,stale,revision:auth.authority_revision}}''',
 'persistent_allow_survives_reload_but_cold_unknown_cannot_read':r'''async()=>{await s.refreshFallbackAuthority();const approved=await policy();return {pass:true,reload_policy:approved.policy_id}}''',
 'manual_read2_preserves_tokens_and_discovery_pages':r'''async()=>{const items=await s.search({slot_id:slot.slot_id,expected_generation:slot.generation,query:'',kind:'recall_search',limit:20,offset:0});const page=await s.read({slot_id:slot.slot_id,expected_generation:slot.generation,document_id:items.items[0].id});const tire=pack.members.find(member=>member.reference.kind==='tire'),doc=pack.documents.find(row=>row.member_key===tire.key),read=await s.read({slot_id:slot.slot_id,expected_generation:slot.generation,document_id:doc.id});return {pass:page.schema==='offline-read-result@2'&&page.member.payload.boundary.formal_campaign_revision===false&&read.member.payload.variant.facts.reference_int.token==='9007199254740993',page_schema:page.schema,token:read.member.payload.variant.facts.reference_int.token}}''',
 'legacy_cannot_read_v2_pack_after_durable_consumed_zero_body':r'''async()=>{
   const legacy=await import(legacyModule),host=await s.status(),intent=await legacy.createFallbackIntent({model:'Fixture Tire',size:'265/40ZR20'},[],'fixture',0,{scope:'api_transport',reason:'api_network_unavailable',query_id:null},crypto.randomUUID());
   const request={intent,slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:host.profile_id,expected_owner_epoch:host.owner_epoch,decision:'allow'},grant=await s.decideFallback(request);startReads();
   const error=await code(s.consumeFallback({grant_id:grant.id,intent})),owner=await dbRead('system','profile'),record=await dbRead('system','fallback-audit'),body=await originalDecrypt({name:'AES-GCM',iv:record.encrypted.iv,additionalData:new TextEncoder().encode(JSON.stringify(['device-fallback-audit@1',owner.profile_id,record.revision]))},owner.key,record.encrypted.ciphertext);
   const states=JSON.parse(new TextDecoder().decode(body)).filter(row=>row.id===grant.id).map(row=>row.state);
   return {pass:error==='OFFLINE_FALLBACK_UNSUPPORTED'&&payloadReads===0&&states.join(',')==='allowed,consumed',error,states,reads:payloadReads};
 }''',
 'shared_pending_sixteen_across_both_schemas':r'''async()=>{
   await s.refreshFallbackAuthority();const legacy=await import(legacyModule),host=await s.status();
   for(let i=0;i<8;i++){const intent=await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,{scope:'api_transport',reason:'api_network_unavailable',query_id:null},crypto.randomUUID());await s.decideFallback({intent,slot_id:slot.slot_id,expected_generation:slot.generation,expected_sha256:slot.sha256,expected_profile_id:host.profile_id,expected_owner_epoch:host.owner_epoch,decision:'allow'})}
   for(let i=0;i<8;i++)await s.decideFallbackV2(await newRequest());startReads();const seventeenth=await code(s.decideFallbackV2(await newRequest()));
   return {pass:seventeenth==='OFFLINE_FALLBACK_CAPACITY'&&payloadReads===0,legacy_pending:8,v2_pending:8,seventeenth,reads:payloadReads};
 }''',
 'never_attempt_burn_is_bounded_at_1024':r'''async()=>{
   await s.refreshFallbackAuthority();startReads();const request=await newRequest('tire',{policy:'never'});let blocked=0,capacity=0;
   for(let i=0;i<1026;i++){const intent={...request.intent,attempt_id:crypto.randomUUID()},result=await code(s.decideFallbackV2({...request,intent}));if(result==='OFFLINE_FALLBACK_NEVER')blocked++;if(result==='OFFLINE_FALLBACK_CAPACITY')capacity++}
   return {pass:blocked===1024&&capacity===2&&payloadReads===0,blocked,capacity,reads:payloadReads};
 }''',
 'false_registered_source_accepts_never_preference_and_unchanged_refresh':r'''async()=>{
   await s.refreshFallbackAuthority();startReads();const approved=await policy('never',{source:'eprel'});await s.refreshFallbackAuthority();const status=await s.fallbackStatus(),saved=status.policies.find(row=>row.policy_id===approved.policy_id),source=status.authority.sources.find(row=>row.source_id==='eprel');
   return {pass:saved.state==='enabled'&&!source.can_query&&!source.can_fetch&&payloadReads===0,state:saved.state,can_query:source.can_query,reads:payloadReads};
 }''',
 'sync_advance_cannot_expand_multi_source_package_whitelist':r'''async()=>{
   await s.refreshFallbackAuthority();startReads();const error=await code(policy('source_allow',{advance:true}));
   return {pass:error==='OFFLINE_FALLBACK_SYNC_ADVANCE_SCOPE_UNAVAILABLE'&&payloadReads===0,error,reads:payloadReads};
 }''',
 'expired_and_clock_rollback_policy_pause_durably':r'''async()=>{
   await s.refreshFallbackAuthority();const approved=await policy(),now=Date.now;Date.now=()=>Date.parse(approved.approved_at)-1;let rollback;
   try{rollback=(await s.fallbackStatus()).policies.find(row=>row.policy_id===approved.policy_id)}finally{Date.now=now}
   const second=await policy();Date.now=()=>Date.parse(second.expires_at)+1;let expired;
   try{expired=(await s.fallbackStatus()).policies.find(row=>row.policy_id===second.policy_id)}finally{Date.now=now}
   const restored=await s.fallbackStatus();return {pass:rollback.state==='paused'&&rollback.reason==='clock_rollback'&&expired.state==='paused'&&expired.reason==='expired'&&restored.policies.every(row=>row.state==='paused'),rollback:rollback.reason,expired:expired.reason};
 }''',
 'session_allow_is_runtime_only_after_reload':r'''async()=>{
   await s.refreshFallbackAuthority();const approved=await policy('session_allow',{scope:{kind:'session',sources:[{source_id:'fixture',access_generation:0,query_kinds:['tire']}]}});return {pass:true,reload_session_policy:approved.policy_id};
 }''',
 'old_missing_binding_status_is_metadata_only_then_manual_read_backfills':r'''async()=>{
   const owner=await dbRead('system','profile'),stored=await dbRead('slots',slot.slot_id),aad=new TextEncoder().encode(JSON.stringify(['offline-vault@1',owner.profile_id,stored.slot_id,stored.generation,stored.owner_epoch,'metadata']));
   const body=await originalDecrypt({name:'AES-GCM',iv:stored.metadata.iv,additionalData:aad},owner.key,stored.metadata.ciphertext),meta=JSON.parse(new TextDecoder().decode(body));delete meta.fallback_binding;
   const iv=crypto.getRandomValues(new Uint8Array(12)),ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad},owner.key,new TextEncoder().encode(JSON.stringify(meta)));stored.metadata={iv,ciphertext};const db=await openDB();await new Promise((resolve,reject)=>{const tx=db.transaction('slots','readwrite');tx.objectStore('slots').put(stored);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();
   startReads();const before=await s.fallbackStatus(),beforeReads=payloadReads,doc=pack.documents[0];await s.read({slot_id:slot.slot_id,expected_generation:slot.generation,document_id:doc.id});const after=await s.fallbackStatus();
   return {pass:before.package_bindings.length===0&&before.missing_package_bindings[0].reason==='scope_metadata_missing'&&beforeReads===0&&after.package_bindings.length===1&&after.package_bindings[0].source_ids.length===3,before_reads:beforeReads,after_binding:after.package_bindings.length,sources:after.package_bindings[0]?.source_ids};
 }''',
}

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    parser.add_argument('--only', help='Comma-separated isolated case names for fixture diagnostics.')
    parser.add_argument('--debug-exceptions', action='store_true')
    args = parser.parse_args()
    cases={name:script for name,script in CASES.items() if not args.only or name in args.only.split(',')}
    assert cases
    output = args.output.resolve()
    assert output.parent == (ROOT/'.artifacts/query-fallback49').resolve() and output.name.startswith('web-v2-')
    output.mkdir(parents=True, exist_ok=False)
    fixture = ROOT/'.artifacts/query-fallback49/producer-v2-samples-a'
    payload = (fixture/'nonempty-pack.json').read_bytes()
    descriptor = json.loads((fixture/'nonempty-descriptor.json').read_text(encoding='utf-8'))
    assert hashlib.sha256(payload).hexdigest() == descriptor['sha256']
    authority_fixture = ROOT/'.artifacts/query-fallback49/source-authority-a'
    catalog = json.loads((authority_fixture/'source-settings.json').read_text(encoding='utf-8'))
    directory = json.loads((authority_fixture/'sources.json').read_text(encoding='utf-8'))
    code = """import {offlineModuleUrl} from './scripts/load_offline_typescript.mjs';import {offlineHostBuild} from './scripts/offline-host-build.mjs';import {pathToFileURL} from 'node:url';
    const base=pathToFileURL(process.cwd()+'/');console.log(JSON.stringify({build:offlineHostBuild(process.cwd(),'web'),modules:{store:await offlineModuleUrl(new URL('apps/web/components/browser-offline-store.ts',base)),sdk:await offlineModuleUrl(new URL('packages/api-client/src/index.ts',base)),legacy:await offlineModuleUrl(new URL('apps/web/components/local-fallback-values.ts',base)),syncValues:await offlineModuleUrl(new URL('apps/web/components/device-sync-values.ts',base))}}));"""
    bundle = json.loads(subprocess.check_output(['node', '--input-type=module', '-e', code], cwd=ROOT, text=True, encoding='utf-8'))
    report = {'schema':'web-device-fallback49-browser@2','state':'running','origin':ORIGIN,'host_build':bundle['build'],
      'real_storage':'Chromium IndexedDB + non-extractable WebCrypto key','normal_api_calls':0,'model_calls':0,
      'metadata':'frozen real catalog plus explicitly synthetic registered sources; intercepted SDK, no live HTTP',
      'denial_runtime_boundary':'Formal UUID identity is canonical only inside the existing owned runtime lifetime. Reload cannot resurrect old grants; fresh @2 remains authority unknown until metadata refresh. Old runtime server decisions are not claimed as currently observed.',
      'fixture_sha256':descriptor['sha256'],'source_sha256':{path:hashlib.sha256((ROOT/path).read_bytes()).hexdigest() for path in SOURCES},
      'checks':[],'unexpected_requests':[]}
    def persist(): (output/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    def route(request):
        if request.request.url == ORIGIN: request.fulfill(status=200,content_type='text/html',body='<!doctype html><title>Private @2 device QA</title>')
        elif request.request.url == ORIGIN+'api/v1/fallback-consents':
            body=json.loads(request.request.post_data)
            assert request.request.method=='POST' and sorted(body)==['decision','query_id','scope'] and body['scope']=='once'
            query=body['query_id']
            response={'id':'00000000-0000-4000-8000-000000000049','decision':'allow' if query.endswith('000000000201') else body['decision'],'scope':'wrong' if query.endswith('000000000204') else 'once','expires_at':'2026-10-01T01:00:00Z'}
            if query.endswith('000000000202'):response['id']='invalid'
            request.fulfill(status=200 if query.endswith('000000000200') else 201,content_type='application/json',body=json.dumps(response))
        else: report['unexpected_requests'].append(request.request.url.split('?')[0]); request.abort()
    persist()
    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(executable_path='C:/Program Files/Google/Chrome/Application/chrome.exe',headless=True)
            try:
                for name, script in cases.items():
                    context = browser.new_context(service_workers='block')
                    try:
                        context.route('**/*',route); page=context.new_page();page.goto(ORIGIN)
                        if args.debug_exceptions:
                            session=context.new_cdp_session(page);session.send('Debugger.enable')
                            report['debug_exceptions']=[]
                            def paused(event):
                                detail=event.get('data',{}).get('description','')
                                if '离线资料' in detail or 'OFFLINE' in detail or 'OfflineError' in detail:
                                    report['debug_exceptions'].append({'description':detail,'frames':[{'function':frame['functionName'],'line':frame['location']['lineNumber']+1} for frame in event.get('callFrames',[])[:8]]})
                                session.send('Debugger.resume')
                            session.on('Debugger.paused',paused);session.send('Debugger.setPauseOnExceptions',{'state':'all'})
                        initialized=page.evaluate(INITIALIZE,{**bundle,'descriptor':descriptor,'payload':base64.b64encode(payload).decode(),'catalog':catalog,'directory':directory})
                        assert initialized['secure'] and initialized['key_extractable'] is False
                        page.evaluate('value=>window.legacyModule=value',bundle['modules']['legacy'])
                        result=page.evaluate(script)
                        if 'reload_denial' in result:
                            denied=result.pop('reload_denial');page.reload()
                            page.evaluate(INITIALIZE,{**bundle,'descriptor':descriptor,'payload':base64.b64encode(payload).decode(),'catalog':catalog,'directory':directory})
                            page.evaluate('value=>window.legacyModule=value',bundle['modules']['legacy'])
                            state=page.evaluate(r'''async old=>{startReads();const cold=await s.fallbackStatus(),v1=await code(s.consumeFallback({grant_id:old.v1.id,intent:old.v1.intent})),v2=await code(s.consumeFallbackV2({grant_id:old.v2.id,intent:old.v2.intent})),failure={scope:'source_response',reason:'upstream_timeout',query_id:old.qid.toUpperCase()},unknown=await code(s.decideFallbackV2(await newRequest('tire',{failure})));await s.refreshFallbackAuthority();const fresh=await s.decideFallbackV2(await newRequest('tire',{failure})),legacy=await import(legacyModule),request=await newRequest('tire',{failure}),intent=await legacy.createFallbackIntent({model:'Fixture Tire'},[],'fixture',0,failure,crypto.randomUUID()),freshV1=await s.decideFallback({...request,intent});return {authority:cold.authority.state,new_runtime:cold.authority.runtime_session_id,old_runtime:old.old_runtime,v1,v2,unknown,fresh:fresh.state,fresh_v1:freshV1.state,reads:payloadReads}}''',denied)
                            result['after_reload']=state;result['pass']=state['authority']=='unknown' and state['old_runtime']!=state['new_runtime'] and state['v1']=='OFFLINE_FALLBACK_USED' and state['v2']=='OFFLINE_FALLBACK_USED' and state['unknown']=='OFFLINE_FALLBACK_AUTHORITY_UNKNOWN' and state['fresh']=='allowed' and state['fresh_v1']=='allowed' and state['reads']==0
                        if 'reload_policy' in result:
                            policy_id=result.pop('reload_policy');page.reload()
                            page.evaluate("async bundle=>{window.process={env:{}};window.__TI_OFFLINE_HOST_BUILD=bundle.build;window.qa=await import(bundle.modules.store);window.s=qa.browserOfflineStorage}",bundle)
                            state=page.evaluate("async()=>{const value=await s.fallbackStatus();return {authority:value.authority.state,policies:value.policies.map(row=>({id:row.policy_id,state:row.state}))}}")
                            result['after_reload']=state;result['pass']=state['authority']=='unknown' and any(row['id']==policy_id and row['state']=='enabled' for row in state['policies'])
                        if 'reload_session_policy' in result:
                            policy_id=result.pop('reload_session_policy');page.reload()
                            page.evaluate("async bundle=>{window.process={env:{}};window.__TI_OFFLINE_HOST_BUILD=bundle.build;window.qa=await import(bundle.modules.store);window.s=qa.browserOfflineStorage}",bundle)
                            state=page.evaluate("async()=>{const value=await s.fallbackStatus();return {authority:value.authority.state,policies:value.policies.map(row=>({id:row.policy_id,state:row.state,reason:row.reason}))}}")
                            result['after_reload']=state;result['pass']=state['authority']=='unknown' and any(row['id']==policy_id and row['state']=='paused' and row['reason']=='runtime_changed' for row in state['policies'])
                        if 'reload_session_policies' in result:
                            policy_ids=result.pop('reload_session_policies');page.reload()
                            page.evaluate("async bundle=>{window.process={env:{}};window.__TI_OFFLINE_HOST_BUILD=bundle.build;window.qa=await import(bundle.modules.store);window.s=qa.browserOfflineStorage}",bundle)
                            state=page.evaluate("async()=>{const value=await s.fallbackStatus();return {authority:value.authority.state,policies:value.policies.map(row=>({id:row.policy_id,state:row.state,reason:row.reason}))}}")
                            result['after_reload']=state;result['pass']=state['authority']=='unknown' and all(any(row['id']==policy_id and row['state']=='paused' and row['reason']=='runtime_changed' for row in state['policies']) for policy_id in policy_ids)
                        report['checks'].append({'name':name,**result});persist()
                    finally: context.close()
            finally: browser.close()
        report['passed']=sum(row['pass'] for row in report['checks']);report['total']=len(cases)
        report['source_drift']=[path for path,expected in report['source_sha256'].items() if hashlib.sha256((ROOT/path).read_bytes()).hexdigest()!=expected]
        report['state']='passed' if report['passed']==report['total'] and not report['unexpected_requests'] and not report['source_drift'] else 'failed';persist()
        print(json.dumps({'report':str(output/'report.json'),'state':report['state'],'passed':report['passed'],'total':report['total']},ensure_ascii=False))
        if report['state']!='passed':raise SystemExit(1)
    except Exception as error:
        report['state']='harness_failed';report['error']=str(error);persist();raise
if __name__=='__main__':main()
